'use client';

import React, { useState } from 'react';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Network,
  Sparkles,
  ZoomIn,
  Loader2,
  ImageOff,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogTrigger,
} from '@/components/ui/dialog';
import type { CallIntelligence } from '@/lib/precall/types';

interface MindMapTabProps {
  intelligence: CallIntelligence;
}

export function MindMapTab({ intelligence }: MindMapTabProps) {
  const [imageError, setImageError] = useState(false);
  const { mindMapImage, summary } = intelligence;

  // If no image, show placeholder
  if (!mindMapImage) {
    return (
      <div className="h-full flex items-center justify-center">
        <Card className="max-w-md mx-auto">
          <CardContent className="p-8 text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-cyan-100 flex items-center justify-center">
              <Network className="h-8 w-8 text-cyan-600" />
            </div>
            <h3 className="font-semibold text-lg mb-2">Mind Map Generating...</h3>
            <p className="text-sm text-muted-foreground mb-4">
              The AI is creating a visual mind map of your call strategy.
              This may take a moment.
            </p>
            <div className="flex items-center justify-center gap-2 text-cyan-600">
              <Loader2 className="h-4 w-4 animate-spin" />
              <span className="text-sm">Powered by Gemini</span>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (imageError) {
    return (
      <div className="h-full flex items-center justify-center">
        <Card className="max-w-md mx-auto">
          <CardContent className="p-8 text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-red-100 flex items-center justify-center">
              <ImageOff className="h-8 w-8 text-red-600" />
            </div>
            <h3 className="font-semibold text-lg mb-2">Image Failed to Load</h3>
            <p className="text-sm text-muted-foreground">
              The mind map image could not be displayed.
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <ScrollArea className="h-full">
      <div className="p-6">
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Network className="h-5 w-5 text-cyan-600" />
            <h2 className="text-lg font-semibold">Call Strategy Mind Map</h2>
            <Badge variant="secondary" className="text-xs">
              <Sparkles className="h-3 w-3 mr-1" />
              AI Generated
            </Badge>
          </div>
          <Dialog>
            <DialogTrigger asChild>
              <Button variant="outline" size="sm">
                <ZoomIn className="h-4 w-4 mr-1" />
                Full Screen
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-[95vw] max-h-[95vh] p-2" aria-describedby={undefined}>
              <img
                src={mindMapImage}
                alt="Call Strategy Mind Map - Full View"
                className="w-full h-full object-contain"
              />
            </DialogContent>
          </Dialog>
        </div>

        {/* Summary */}
        {summary && (
          <Card className="mb-4 bg-gradient-to-r from-cyan-50 to-blue-50 border-cyan-200">
            <CardContent className="p-3">
              <p className="text-sm text-muted-foreground">
                <strong>Context:</strong> {summary}
              </p>
            </CardContent>
          </Card>
        )}

        {/* Mind Map Image */}
        <Card className="overflow-hidden">
          <CardContent className="p-0">
            <img
              src={mindMapImage}
              alt="Call Strategy Mind Map"
              className="w-full h-auto"
              onError={() => setImageError(true)}
            />
          </CardContent>
        </Card>

        {/* Attribution */}
        <div className="mt-4 text-center text-xs text-muted-foreground">
          Generated by Gemini 3 Pro Image Preview
        </div>
      </div>
    </ScrollArea>
  );
}

export default MindMapTab;

