// @vitest-environment node
import { describe, expect, it, vi } from 'vitest';
import { randomUUID } from 'node:crypto';
import { createDockerCodingSandbox } from './coding-worker-docker.js';
import { CodingProposalSchema, CodingWorkerError, codingHash, contentHash, prepareCodingSpec } from './coding-worker-contracts.js';
import { createCodingWorkerService } from './coding-worker-service.js';

const tenantId = 'a9ae8baa-3bc2-4dc1-a151-f0449ee28dc7';
const solutionId = '31b3b478-93a1-41fa-9dfa-46f0f757c4c9';
const runId = 'de002e7a-86be-47f3-81f7-01e8ac0649b9';
const scope = { tenantId, userId: 'user_codingFixture', solutionId, runId };
const image = 'sha256:307d6065be25619aa24cfc63a7c2f04ca56d084a08c05c8e9f189a89f353b1ec';
const descriptor = { kind: 'node_offline_v1', image, isolation: 'local_fixture', productionEligible: false };
function proposal(source = 'export const total = (a,b) => a+b;') {
  const original = 'export const total = (a,b) => a-b;';
  return { kind: 'node_source_patch_v1', title: 'Fix total calculation', source: [{ path: 'src/total.mjs', content: original }],
    changes: [{ path: 'src/total.mjs', previousHash: contentHash(original), content: source }],
    tests: [{ path: 'total.test.mjs', content: "import test from 'node:test'; import assert from 'node:assert/strict'; import {total} from '/workspace/src/total.mjs'; test('adds',()=>assert.equal(total(2,3),5));" }],
    outputs: ['src/total.mjs'], timeoutMs: 10000 };
}
function completeReceipt(scope, job) {
  const artifacts = job.spec.outputs.map(path => { const content = job.spec.prepared.find(file => file.path === path).content;
    return { path, content, hash: contentHash(content), bytes: Buffer.byteLength(content) }; });
  const meta = artifacts.map(({ path, hash, bytes }) => ({ path, hash, bytes }));
  return { status: 'succeeded', artifacts, evidence: { kind: 'isolated_coding_worker', specHash: job.spec_hash, executionId: job.execution_id,
    sourceHash: job.spec.sourceHash, preparedHash: job.spec.preparedHash, testsHash: job.spec.testsHash, scopeHash: codingHash(scope), runtime: job.spec.runtime,
    boundary: { network: 'none', credentials: 'none', testsReadOnly: true }, log: 'actual fixture command output', startedAt: new Date().toISOString(), completedAt: new Date().toISOString(),
    command: { kind: 'node_test_v1', exitCode: 0, timedOut: false, outputTruncated: false }, artifacts: meta, artifactHash: codingHash(meta), cleanup: { status: 'removed' } } };
}
// Synthetic unit fixture only. Production uses the separately tested PostgreSQL
// store; business execution and artifacts are never generated by this fixture.
function memoryStore() {
  const rows = new Map();
  const owned = (scope, id) => { const value = rows.get(id); if (!value || value.tenant_id !== scope.tenantId || value.owner_user_id !== scope.userId || value.solution_id !== scope.solutionId || value.run_id !== scope.runId) throw new CodingWorkerError('CODING_JOB_NOT_FOUND', 404); return value; };
  return {
    rows,
    async claim(executionId) {
      const row = [...rows.values()].find((entry) => entry.status === 'queued');
      if (!row) return null;
      Object.assign(row, { status: 'running', execution_id: executionId, execution_deadline: new Date(Date.now() + 120000).toISOString(), row_version: row.row_version + 1 });
      return { tenantId: row.tenant_id, userId: row.owner_user_id, solutionId: row.solution_id, runId: row.run_id, jobId: row.id, executionId };
    },
    async insert(scope, value) {
      const previous = [...rows.values()].find((row) => row.request_key === value.key && row.tenant_id === scope.tenantId && row.solution_id === scope.solutionId);
      if (previous) { if (previous.spec_hash !== value.specHash) throw new CodingWorkerError('CODING_IDEMPOTENCY_CONFLICT'); return structuredClone(previous); }
      const row = { tenant_id: scope.tenantId, owner_user_id: scope.userId, solution_id: scope.solutionId, run_id: scope.runId,
        id: value.id, spec: value.spec, spec_hash: value.specHash, request_key: value.key, status: 'proposed', row_version: 0,
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(), evidence: null, artifacts: null };
      rows.set(row.id, row); return structuredClone(row);
    },
    async read(scope, id) { return structuredClone(owned(scope, id)); },
    async list(scope) { return [...rows.values()].filter((row) => row.tenant_id === scope.tenantId && row.owner_user_id === scope.userId && row.solution_id === scope.solutionId && row.run_id === scope.runId).map((row) => structuredClone(row)); },
    async transition(scope, id, change) {
      const row = owned(scope, id);
      if (!change.from.includes(row.status)) return { changed: false, job: structuredClone(row) };
      if (change.expectedVersion !== undefined && row.row_version !== change.expectedVersion) throw new CodingWorkerError('CODING_VERSION_CONFLICT');
      if (change.specHash && row.spec_hash !== change.specHash) throw new CodingWorkerError('CODING_SPEC_CONFLICT');
      Object.assign(row, { status: change.status, row_version: row.row_version + 1 }, change.approvalId ? { approval_id: change.approvalId } : {},
        change.executionId ? { execution_id: change.executionId, execution_deadline: change.deadline } : {},
        change.evidence ? { evidence: change.evidence, artifacts: change.artifacts } : {});
      return { changed: true, job: structuredClone(row) };
    },
  };
}

describe('approved isolated coding contract', () => {
  it('binds exact source, edits, tests, command, limits and runtime into approval', () => {
    const spec = prepareCodingSpec(proposal(), descriptor);
    expect(spec.prepared[0].content).toContain('a+b');
    expect(spec.sourceHash).not.toBe(spec.preparedHash);
    expect(spec).toMatchObject({ network: 'none', credentials: 'none', repositoryEffects: 'artifact_only', command: 'node_test_v1' });
    expect(() => prepareCodingSpec({ ...proposal(), changes: [{ ...proposal().changes[0], previousHash: 'f'.repeat(64) }] }, descriptor)).toThrow('CODING_SOURCE_VERSION_CONFLICT');
    expect(codingHash(spec)).not.toBe(codingHash({ ...spec, tests: [] }));
  });
  it.each(['../secret', '/etc/passwd', '.env', 'src/../secret', 'src//foo', 'src/.git/config', 'node_modules/pkg.js', '-bad'])('rejects source path %s', (path) => {
    expect(CodingProposalSchema.safeParse({ ...proposal(), source: [{ path, content: 'x' }] }).success).toBe(false);
  });
  it('rejects arbitrary commands, broad resources, duplicate paths and unpinned/weak production runtimes', () => {
    expect(CodingProposalSchema.safeParse({ ...proposal(), command: 'curl https://metadata' }).success).toBe(false);
    expect(CodingProposalSchema.safeParse({ ...proposal(), timeoutMs: 120001 }).success).toBe(false);
    expect(CodingProposalSchema.safeParse({ ...proposal(), tests: [proposal().tests[0], proposal().tests[0]] }).success).toBe(false);
    expect(() => createDockerCodingSandbox({ image: 'node:latest' })).toThrow('CODING_PINNED_IMAGE_REQUIRED');
    expect(() => createDockerCodingSandbox({ image, isolation: 'local_fixture' })).toThrow('CODING_ISOLATION_REQUIRED');
  });
});

describe('durable approval and scoped n8n dispatch service', () => {
  function fixture(run = async (scope, job) => completeReceipt(scope, job)) {
    const store = memoryStore(); const sandbox = { descriptor, run: vi.fn(run), reconcile: vi.fn(async () => ({ status: 'removed' })) };
    const service = createCodingWorkerService({ repository: { resolveTenant: async () => tenantId }, store, sandbox, signingKey: Buffer.alloc(32, 3) });
    return { service, store, sandbox };
  }
  async function approved(service) {
    const created = await service.create(scope, solutionId, { runId, proposal: proposal() }, 'create-code-fixture');
    const command = { runId, expectedVersion: created.job.rowVersion, specHash: created.job.specHash };
    await service.approve(scope, solutionId, created.job.id, command, 'approve-code-fixture');
    const capability = await service.dispatchCapability(scope, solutionId, created.job.id, command);
    return { ...capability, command };
  }
  it('cannot execute a proposal before separate exact-hash user approval', async () => {
    const { service, sandbox } = fixture(); const created = await service.create(scope, solutionId, { runId, proposal: proposal() }, 'create-code-fixture');
    await expect(service.dispatchCapability(scope, solutionId, created.job.id, { runId, specHash: created.job.specHash })).rejects.toThrow('CODING_DISPATCH_NOT_APPROVED');
    await expect(service.approve(scope, solutionId, created.job.id, { runId, expectedVersion: 0, specHash: 'f'.repeat(64) }, 'approve-code-fixture')).rejects.toThrow('CODING_SPEC_CONFLICT');
    expect(sandbox.run).not.toHaveBeenCalled();
  });
  it('allows one real dispatch only, survives service reconstruction and never returns code in n8n receipts', async () => {
    const { service, sandbox, store } = fixture(); const capability = await approved(service);
    const first = await service.dispatch(capability.token, capability.jobId, capability.specHash);
    expect(first).toMatchObject({ job: { status: 'queued' }, replayed: false });
    expect(sandbox.run).not.toHaveBeenCalled();
    await service.advanceOne();
    const restarted = createCodingWorkerService({ repository: { resolveTenant: async () => tenantId }, store, sandbox, signingKey: Buffer.alloc(32, 3) });
    expect(await restarted.dispatch(capability.token, capability.jobId, capability.specHash)).toMatchObject({ replayed: true });
    expect(sandbox.run).toHaveBeenCalledTimes(1); expect(JSON.stringify(first)).not.toContain('export const');
  });
  it('denies cross-user/run/solution and forged or substituted dispatch claims', async () => {
    const { service, sandbox } = fixture(); const capability = await approved(service);
    for (const [auth, solution, run] of [[{ userId: 'user_other' }, solutionId, runId], [scope, randomUUID(), runId], [scope, solutionId, randomUUID()]])
      await expect(service.read(auth, solution, capability.jobId, { runId: run })).rejects.toThrow('CODING_JOB_NOT_FOUND');
    await expect(service.dispatch(`${capability.token}x`, capability.jobId, capability.specHash)).rejects.toThrow('CODING_DISPATCH_DENIED');
    await expect(service.dispatch(capability.token, randomUUID(), capability.specHash)).rejects.toThrow('CODING_DISPATCH_DENIED');
    await expect(service.dispatch(capability.token, capability.jobId, 'f'.repeat(64))).rejects.toThrow('CODING_DISPATCH_DENIED');
    expect(sandbox.run).not.toHaveBeenCalled();
  });
  it('persists unknown outcomes and never automatically retries missing cleanup/evidence', async () => {
    const { service, sandbox } = fixture(async () => { throw new Error('interrupted'); }); const capability = await approved(service);
    await service.dispatch(capability.token, capability.jobId, capability.specHash); await service.advanceOne();
    expect(await service.read(scope, solutionId, capability.jobId, { runId })).toMatchObject({ job: { status: 'outcome_unknown' } });
    await service.dispatch(capability.token, capability.jobId, capability.specHash); expect(sandbox.run).toHaveBeenCalledTimes(1);
  });
  it('rejects incomplete or contradictory success receipts rather than claiming success', async () => {
    for (const run of [async (_scope, job) => ({ status: 'succeeded', artifacts: [], evidence: { specHash: job.spec_hash, executionId: job.execution_id, cleanup: { status: 'removed' } } }),
      async (scope, job) => { const result = completeReceipt(scope, job); result.evidence.command.exitCode = 1; return result; },
      async (scope, job) => { const result = completeReceipt(scope, job); result.artifacts[0].content = 'substituted'; return result; }]) {
      const { service } = fixture(run); const cap = await approved(service); await service.dispatch(cap.token, cap.jobId, cap.specHash);
      expect(await service.advanceOne()).toMatchObject({ processed: true, status: 'outcome_unknown' });
      expect((await service.read(scope, solutionId, cap.jobId, { runId })).job.artifacts).toEqual([]);
    }
  });
  it('reports authoritative unknown after reconciliation wins a race with a late success', async () => {
    let complete; const f = fixture(async (scope, job) => new Promise(resolve => { complete = () => resolve(completeReceipt(scope, job)); }));
    const cap = await approved(f.service); await f.service.dispatch(cap.token, cap.jobId, cap.specHash);
    const waiting = f.service.advanceOne(); await vi.waitFor(() => expect(complete).toBeTypeOf('function'));
    const row = f.store.rows.get(cap.jobId); row.status = 'outcome_unknown'; row.evidence = { cleanup: { status: 'removed' } }; row.row_version += 1;
    complete(); expect(await waiting).toMatchObject({ processed: true, status: 'outcome_unknown' });
  });
});

describe.runIf(process.env.ORQALY_CODING_RUNTIME_LIVE === '1')('actual disposable isolated coding runtime', () => {
  const sandbox = createDockerCodingSandbox({ image, isolation: 'local_fixture', allowLocalFixture: true });
  async function execute(selected) {
    const spec = prepareCodingSpec(selected, sandbox.descriptor);
    return sandbox.run(scope, { id: randomUUID(), spec, spec_hash: codingHash(spec), execution_id: randomUUID() });
  }
  it('applies an actual code change, runs immutable tests and returns the changed source artifact', async () => {
    const actual = await execute(proposal());
    expect(actual, JSON.stringify(actual)).toMatchObject({ status: 'succeeded', evidence: { command: { exitCode: 0 }, cleanup: { status: 'removed' } } });
    expect(actual.artifacts[0]).toMatchObject({ path: 'src/total.mjs', content: proposal().changes[0].content, hash: contentHash(proposal().changes[0].content) });
  }, 60000);
  it('proves no Docker socket, host environment, writable approved tests/root or metadata/network access', async () => {
    const selected = proposal("import fs from 'node:fs';import net from 'node:net'; export const total=(a,b)=>a+b; export const isolated=async()=>{let rejected=0;for(const p of ['/var/run/docker.sock','/root/.config/gcloud/application_default_credentials.json']){try{fs.readFileSync(p)}catch{rejected++}}for(const p of ['/approved-tests/total.test.mjs','/etc/owned']){try{fs.writeFileSync(p,'bad')}catch{rejected++}}const blocked=await new Promise(resolve=>{const s=net.connect({host:'169.254.169.254',port:80});s.on('connect',()=>{s.destroy();resolve(false)});s.on('error',()=>resolve(true));s.setTimeout(300,()=>{s.destroy();resolve(true)})});return rejected===4&&blocked&&!process.env.CLERK_SECRET_KEY&&!process.env.GOOGLE_APPLICATION_CREDENTIALS};");
    selected.tests[0].content += "import {isolated} from '/workspace/src/total.mjs'; test('isolation',async()=>assert.equal(await isolated(),true));";
    const actual = await execute(selected);
    expect(actual, JSON.stringify(actual)).toMatchObject({ status: 'succeeded', evidence: { boundary: { codeUid: 10001 }, cleanup: { status: 'removed' } } });
  }, 60000);
  it('returns actual failing exit evidence instead of inventing successful test output', async () => {
    const actual = await execute(proposal('export const total=(a,b)=>a-b;'));
    expect(actual, JSON.stringify(actual)).toMatchObject({ status: 'failed', artifacts: [], evidence: { command: { exitCode: 1 }, cleanup: { status: 'removed' } } });
  }, 60000);
  it('kills the entire bounded container on timeout and confirms cleanup', async () => {
    const actual = await execute({ ...proposal('export const total=(a,b)=>{while(true){}};'), timeoutMs: 1000 });
    expect(actual, JSON.stringify(actual)).toMatchObject({ status: 'timed_out', artifacts: [], evidence: { command: { timedOut: true }, cleanup: { status: 'removed' } } });
  }, 60000);
});
