/**
 * agentResumePdf — generates a printable resume HTML in a new window.
 * Uses window.print() for browser-native PDF export.
 */

function esc(s) {
  if (!s) return '';
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function printAgentResume(agent, resume) {
  if (!resume) return;

  const name = esc(agent.role || agent.name || 'Agent');
  const category = esc(agent.category || '');
  const headline = esc(resume.headline || '');
  const summary = esc(resume.summary || '');
  const skills = Array.isArray(resume.skills) ? resume.skills : [];
  const experience = Array.isArray(resume.experience) ? resume.experience : [];
  const stats = resume.stats || {};
  const certs = Array.isArray(resume.certifications) ? resume.certifications : [];

  const skillsHtml = skills.length
    ? `<div class="section"><h2>Skills</h2><div class="skills">${skills.map((s) => `<span class="chip">${esc(s)}</span>`).join('')}</div></div>`
    : '';

  const expRows = experience
    .map(
      (e) =>
        `<tr><td>${esc(e.title)}</td><td style="text-align:center">${e.count || 0}</td><td style="text-align:center">${e.successRate != null ? `${e.successRate}%` : '—'}</td></tr>`
    )
    .join('');
  const expHtml = expRows
    ? `<div class="section"><h2>Experience</h2><table><thead><tr><th>Category</th><th style="text-align:center">Tasks</th><th style="text-align:center">Success Rate</th></tr></thead><tbody>${expRows}</tbody></table></div>`
    : '';

  const statsHtml = `<div class="section"><h2>Performance</h2><div class="stats-grid">
    <div class="stat"><span class="stat-val">${stats.totalTasks ?? 0}</span><span class="stat-lbl">Total Tasks</span></div>
    <div class="stat"><span class="stat-val">${stats.completedTasks ?? 0}</span><span class="stat-lbl">Completed</span></div>
    <div class="stat"><span class="stat-val">${stats.successRate != null ? `${stats.successRate}%` : '—'}</span><span class="stat-lbl">Success Rate</span></div>
    <div class="stat"><span class="stat-val">$${Number(stats.avgCostPerTask || 0).toFixed(4)}</span><span class="stat-lbl">Avg Cost</span></div>
    <div class="stat"><span class="stat-val">$${Number(stats.totalCostUsd || 0).toFixed(2)}</span><span class="stat-lbl">Total Cost</span></div>
  </div></div>`;

  const certsHtml = certs.length
    ? `<div class="section"><h2>Certifications</h2><ul>${certs.map((c) => `<li>${esc(c)}</li>`).join('')}</ul></div>`
    : '';

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${name} — Resume</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',system-ui,-apple-system,sans-serif;color:#1a1a1a;max-width:720px;margin:0 auto;padding:40px 32px;line-height:1.5}
.header{border-bottom:2px solid #2563eb;padding-bottom:16px;margin-bottom:24px}
.header h1{font-size:24px;font-weight:700;color:#111}
.header .category{font-size:13px;color:#666;margin-top:2px;text-transform:uppercase;letter-spacing:0.5px}
.header .headline{font-size:15px;color:#2563eb;margin-top:6px;font-weight:500}
.section{margin-bottom:20px}
.section h2{font-size:14px;text-transform:uppercase;letter-spacing:0.8px;color:#2563eb;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin-bottom:10px}
.summary{font-size:14px;color:#333;line-height:1.6}
.skills{display:flex;flex-wrap:wrap;gap:6px}
.chip{background:#eff6ff;color:#2563eb;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:500}
table{width:100%;border-collapse:collapse;font-size:13px}
thead th{text-align:left;font-weight:600;padding:6px 8px;border-bottom:2px solid #e5e7eb;color:#555}
tbody td{padding:6px 8px;border-bottom:1px solid #f3f4f6}
.stats-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}
.stat{text-align:center}
.stat-val{display:block;font-size:18px;font-weight:700;color:#111}
.stat-lbl{font-size:11px;color:#888;text-transform:uppercase}
ul{list-style:disc inside;font-size:13px;color:#333}
.footer{margin-top:28px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:11px;color:#aaa;text-align:center}
@media print{body{padding:20px}@page{margin:20mm}}
</style></head><body>
<div class="header">
  <h1>${name}</h1>
  ${category ? `<div class="category">${category}</div>` : ''}
  ${headline ? `<div class="headline">${headline}</div>` : ''}
</div>
${summary ? `<div class="section"><h2>Summary</h2><p class="summary">${summary}</p></div>` : ''}
${skillsHtml}
${expHtml}
${statsHtml}
${certsHtml}
<div class="footer">Generated by Orqaly · ${new Date().toLocaleDateString()}</div>
</body></html>`;

  const w = window.open('', '_blank');
  if (w) {
    w.document.write(html);
    w.document.close();
    setTimeout(() => w.print(), 400);
  }
}
