/**
 * Knowledge Base category group mapping and display constants.
 * Maps raw DB category values into user-friendly groups for filtering and card rendering.
 * Raw category values are NEVER changed — backwards compatible with all pipelines.
 */

// ── Category Groups ──────────────────────────────────────────────
export const CATEGORY_GROUPS = {
  Goals: ['goal-plan', 'goal-output', 'goal-report', 'goal-retrospective'],
  Agents: ['agent-report', 'agent-work-memory', 'job-memory'],
  Quality: ['calibration_sample', 'quality_criteria', 'library_example', 'osja_review'],
  System: ['system_flag'],
  Bookmarks: ['bookmark'],
  General: ['general', 'technical', 'business', 'legal', 'support', 'other'],
};

// ── Display list for Select/chips ────────────────────────────────
export const CATEGORY_GROUP_LIST = [
  { value: '', label: 'All Categories' },
  { value: 'Goals', label: 'Goals', color: '#2196f3' },
  { value: 'Agents', label: 'Agents', color: '#00bcd4' },
  { value: 'Quality', label: 'Quality', color: '#ff9800' },
  { value: 'System', label: 'System', color: '#f44336' },
  { value: 'Bookmarks', label: 'Bookmarks', color: '#D97706' },
  { value: 'General', label: 'General', color: '#78909c' },
];

// ── Reverse lookup: raw category → group name ────────────────────
const _reverseMap = {};
for (const [group, cats] of Object.entries(CATEGORY_GROUPS)) {
  for (const cat of cats) _reverseMap[cat] = group;
}

export function groupForCategory(rawCategory) {
  return _reverseMap[rawCategory] || 'Other';
}

export function colorForGroup(groupName) {
  return CATEGORY_GROUP_LIST.find((g) => g.value === groupName)?.color || '#78909c';
}

// ── Freshness helpers ────────────────────────────────────────────
const DAY_MS = 86_400_000;
const WEEK_MS = 7 * DAY_MS;

export function getFreshness(dateStr) {
  if (!dateStr) return 'older';
  const age = Date.now() - new Date(dateStr).getTime();
  if (age < DAY_MS) return 'today';
  if (age < WEEK_MS) return 'week';
  return 'older';
}

export const FRESHNESS_COLORS = {
  today: '#4caf50',
  week: '#ff9800',
  older: '#9e9e9e',
};

// ── Source badge helpers ─────────────────────────────────────────
const AUTO_SOURCES = ['goal-orchestrator', 'pulse', 'osja', 'execute-task', 'library-calibration'];

export function isAutoGenerated(source) {
  if (!source) return false;
  const s = source.toLowerCase();
  return AUTO_SOURCES.some((a) => s.includes(a));
}

// ── Knowledge "type" (the KB page tabs) for a single document ─────
// Mirrors the tab filters in KnowledgeBase.jsx so a doc maps to one of the
// seven user-facing types. Used for the activity log + Home Data Operations.
export const KB_TYPE = {
  DOCUMENTS: 'Documents',
  BOOKMARKS: 'Bookmarks',
  PHONE_CONTACT: 'Phone Contact',
  MAIL_CONTACT: 'Mail Contact',
  GOALS: 'Goals',
  AGENT_MEMORY: 'Agent Memory',
  REPORTS: 'Reports',
  GITHUB_OFFERS: 'Github offers',
};

export function docToType(doc) {
  if (!doc) return KB_TYPE.DOCUMENTS;
  const category = doc.category || '';
  const tags = Array.isArray(doc.tags) ? doc.tags : [];
  const contactType = doc.contact_type || doc.metadata?.contact_type;
  if (contactType === 'phone') return KB_TYPE.PHONE_CONTACT;
  if (contactType === 'mail' || contactType === 'email') return KB_TYPE.MAIL_CONTACT;
  if (category === 'github-offer' || tags.includes('github-offer')) return KB_TYPE.GITHUB_OFFERS;
  // Bookmarks: link docs saved by a human or agent. Checked before the
  // agent-memory/reports branches so agent-owned bookmarks aren't miscategorized.
  if (doc.content_type === 'link' && (category === 'bookmark' || tags.includes('bookmark')))
    return KB_TYPE.BOOKMARKS;
  if (
    ['goal-report', 'goal-retrospective', 'agent-report'].includes(category) ||
    tags.includes('report') ||
    tags.includes('final')
  ) {
    return KB_TYPE.REPORTS;
  }
  if (
    doc.owner_type === 'agent' ||
    ['job-memory', 'agent-work-memory'].includes(category) ||
    tags.includes('pulse-learning') ||
    tags.includes('auto-memory')
  ) {
    return KB_TYPE.AGENT_MEMORY;
  }
  if (['goal-plan', 'goal-output'].includes(category) || tags.includes('goal'))
    return KB_TYPE.GOALS;
  return KB_TYPE.DOCUMENTS;
}
