-- ===========================================================================
-- 111_skill_forge.sql — Skill Forge columns
--
-- Adds metadata for AI-generated skills so they can be tracked, reviewed,
-- and approved before they influence any agent.
-- ===========================================================================

-- 1. Source of the skill — human-authored vs generated by the Skill Forge
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'skill_generation_source'
  ) THEN
    CREATE TYPE skill_generation_source AS ENUM ('human', 'forge');
  END IF;
END $$;

-- 2. Moderation status for forge-generated skills
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'skill_status'
  ) THEN
    CREATE TYPE skill_status AS ENUM ('active', 'pending_review', 'rejected');
  END IF;
END $$;

-- 3. New columns on agent_skill_packs (idempotent)
ALTER TABLE agent_skill_packs
  ADD COLUMN IF NOT EXISTS generation_source skill_generation_source NOT NULL DEFAULT 'human';

ALTER TABLE agent_skill_packs
  ADD COLUMN IF NOT EXISTS status skill_status NOT NULL DEFAULT 'active';

ALTER TABLE agent_skill_packs
  ADD COLUMN IF NOT EXISTS forge_test_report jsonb;

-- 4. Index for filtering pending-review skills in the UI
CREATE INDEX IF NOT EXISTS idx_agent_skill_packs_status_user
  ON agent_skill_packs (user_id, status)
  WHERE status = 'pending_review';

COMMENT ON COLUMN agent_skill_packs.generation_source IS 'Whether this skill was authored by a human or generated by Skill Forge';
COMMENT ON COLUMN agent_skill_packs.status IS 'active = visible/installable; pending_review = awaiting user approval after forge generation; rejected = failed forge tests';
COMMENT ON COLUMN agent_skill_packs.forge_test_report IS 'JSONB: { red_team: [{prompt, response, verdict}], behaviour: [{prompt, response, verdict}], passed: boolean }';
