/**
 * AI Recommendations — loads AI-generated recommendations from the database.
 * Recommendations are generated by a Vercel cron job every 24h using Groq LLM.
 * Falls back to rule-based recommendations when no DB data is available.
 */
import { hasSupabase, supabase } from '../lib/supabase';

const FUNNEL_STATUSES = [
  'Contacted',
  'Meeting Scheduled',
  'Proposal Sent',
  'Agreed start date',
  'Working',
];

/**
 * Get AI recommendations for a partner.
 * Tries Supabase first; falls back to rule-based if no DB results.
 */
export async function getRecommendations(partner, context = {}) {
  const partnerId = partner?.id;
  if (!partnerId) return [];

  // Try loading from database first
  if (hasSupabase()) {
    try {
      const dbRecs = await loadRecommendationsFromDB(partnerId);
      if (dbRecs.length > 0) return dbRecs;
    } catch (err) {
      console.warn('[aiRecommendations] DB load failed, using fallback:', err.message);
    }
  }

  // Fallback: rule-based recommendations
  return generateRuleBasedRecommendations(partner, context);
}

/**
 * Get the timestamp of the last AI analysis for a partner.
 */
export async function getLastAnalyzedAt(partnerId) {
  if (!hasSupabase() || !partnerId) return null;
  try {
    const { data } = await supabase
      .from('partner_ai_recommendations')
      .select('analyzed_at')
      .eq('partner_id', partnerId)
      .order('analyzed_at', { ascending: false })
      .limit(1);
    return data?.[0]?.analyzed_at || null;
  } catch {
    return null;
  }
}

async function loadRecommendationsFromDB(partnerId) {
  const { data, error } = await supabase
    .from('partner_ai_recommendations')
    .select('*')
    .eq('partner_id', partnerId)
    .order('priority', { ascending: true });

  if (error) throw error;
  if (!data || data.length === 0) return [];

  const priorityOrder = { high: 0, medium: 1, low: 2 };
  return data
    .map((row) => ({
      id: row.id,
      title: row.title,
      description: row.description || '',
      steps: Array.isArray(row.steps) ? row.steps : [],
      priority: row.priority || 'medium',
      category: row.category || 'general',
      analyzedAt: row.analyzed_at,
      isAI: true,
    }))
    .sort((a, b) => (priorityOrder[a.priority] ?? 1) - (priorityOrder[b.priority] ?? 1));
}

/**
 * Fallback: rule-based recommendations (no API needed).
 */
function generateRuleBasedRecommendations(partner, context = {}) {
  const recs = [];
  const pid = partner?.id || '';
  const funnelStatus = partner?.funnelStatus || 'Contacted';
  const agreement = partner?.agreement || '';
  const tasks = Array.isArray(partner?.tasks) ? partner.tasks : [];
  const campaigns = Array.isArray(partner?.campaigns) ? partner.campaigns : [];
  const meetingsCount = context.meetingsCount ?? 0;
  const hasRecentMeeting = context.hasRecentMeeting ?? false;
  const financeDebt = context.financeDebt ?? 0;

  const funnelIndex = FUNNEL_STATUSES.indexOf(funnelStatus);
  const todoTasks = tasks.filter((t) => t.status === 'todo' || t.status === 'inProgress');
  const overdueTasks = tasks.filter((t) => {
    if (!t.dueDate) return false;
    return new Date(t.dueDate) < new Date() && t.status !== 'done';
  });
  const activeCampaigns = campaigns.filter(
    (c) => (c.metrics?.ftd || 0) > 0 || (c.metrics?.clicks || 0) > 0
  );

  if (funnelIndex >= 0 && funnelIndex < FUNNEL_STATUSES.length - 1) {
    const next = FUNNEL_STATUSES[funnelIndex + 1];
    recs.push({
      id: `rec-funnel-${pid}`,
      title: 'Advance funnel stage',
      description: `Partner is at "${funnelStatus}". Consider moving to "${next}" when ready.`,
      steps: [
        `Confirm all criteria for "${next}" are met.`,
        'Update funnel status in the profile when the step is completed.',
        'Add a history note or reminder for the next touchpoint.',
      ],
      priority: funnelIndex <= 1 ? 'high' : 'medium',
      category: 'growth',
    });
  }

  if (meetingsCount === 0 && funnelIndex >= 0) {
    recs.push({
      id: `rec-meeting-${pid}`,
      title: 'Schedule first meeting',
      description: 'No meetings recorded yet. A kickoff or discovery call can align expectations.',
      steps: [
        'Use the Meetings section to create a new meeting.',
        'Add agenda: goals, traffic, compliance, and timeline.',
        'After the meeting, use the summary to create tasks.',
      ],
      priority: 'high',
      category: 'engagement',
    });
  }

  if (overdueTasks.length > 0) {
    recs.push({
      id: `rec-overdue-${pid}`,
      title: 'Address overdue tasks',
      description: `${overdueTasks.length} task(s) past due. Resolving them keeps the relationship on track.`,
      steps: [
        'Open Tasks and filter by this partner.',
        'Complete or reschedule overdue items.',
        'Add a note in History if the delay was agreed with the partner.',
      ],
      priority: 'high',
      category: 'risk',
    });
  }

  if (todoTasks.length >= 4) {
    recs.push({
      id: `rec-tasks-${pid}`,
      title: 'Prioritize open tasks',
      description: `${todoTasks.length} tasks in progress. Focus on the highest-priority items first.`,
      steps: [
        'Review task priorities in Tasks.',
        'Close or defer lower-priority tasks if needed.',
        'Consider a short sync with the partner to reprioritize.',
      ],
      priority: 'medium',
      category: 'optimization',
    });
  }

  if (funnelStatus === 'Working' && activeCampaigns.length === 0 && campaigns.length > 0) {
    recs.push({
      id: `rec-campaigns-${pid}`,
      title: 'Activate or review campaigns',
      description: 'Partner is Working but no campaigns show recent activity.',
      steps: [
        'Review the Campaigns drawer and confirm tracking links.',
        'Ensure the partner has creatives and landing pages they need.',
        'If paused, agree on a go-live date and add a reminder.',
      ],
      priority: 'high',
      category: 'growth',
    });
  }

  if (financeDebt > 0) {
    recs.push({
      id: `rec-debt-${pid}`,
      title: 'Outstanding payments',
      description: 'There is unpaid balance. Timely payments support trust and continuity.',
      steps: [
        'Confirm payment terms and due dates with finance.',
        'Add a payment in the Finance section when processed.',
        'Optionally add a History note when the partner is notified.',
      ],
      priority: 'high',
      category: 'risk',
    });
  }

  if (agreement && funnelStatus === 'Working' && !hasRecentMeeting) {
    recs.push({
      id: `rec-checkin-${pid}`,
      title: 'Schedule a check-in',
      description: `No recent meeting. A short check-in helps align on ${agreement} performance.`,
      steps: [
        'Create a short meeting (15-30 min) in Meetings.',
        'Prepare: current FTD/CR, any creatives or geo tests.',
        'After the call, add a note and follow-up tasks.',
      ],
      priority: 'medium',
      category: 'engagement',
    });
  }

  if (funnelIndex <= 2 && campaigns.length === 0) {
    recs.push({
      id: `rec-materials-${pid}`,
      title: 'Share onboarding materials',
      description: 'Partner is in early stage. Sending materials speeds up launch.',
      steps: [
        'Upload or link materials in the Materials section.',
        'Share links via your usual channel.',
        'Add a History note and set a follow-up reminder.',
      ],
      priority: 'medium',
      category: 'engagement',
    });
  }

  recs.sort((a, b) => {
    const order = { high: 0, medium: 1, low: 2 };
    return (
      (order[a.priority] ?? 1) - (order[b.priority] ?? 1) || (a.id || '').localeCompare(b.id || '')
    );
  });

  return recs;
}

export const aiRecommendationsService = {
  getRecommendations,
  getLastAnalyzedAt,
};

export default aiRecommendationsService;
