steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'apps/axwise-site/Dockerfile', '-t', '${_IMAGE}', 'apps/axwise-site']
images: ['${_IMAGE}']
substitutions:
  _IMAGE: europe-west4-docker.pkg.dev/$PROJECT_ID/axwise-v2/axwise-site:$BUILD_ID
options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
