/**
 * KBCategoryCard - Per-category card renderer for Knowledge Base documents.
 * Renders specialized layouts based on category group (Goals, Agents, Quality,
 * System, General) with a clean, readable, production layout: soft header avatar,
 * legible title + snippet, compact metadata chips, tag row, and hover-reveal
 * actions (always visible on touch).
 */
import { Box, Paper, Typography, Chip, IconButton, Tooltip, useTheme, alpha } from '@mui/material';
import TrackChangesOutlinedIcon from '@mui/icons-material/TrackChangesOutlined';
import SmartToyOutlinedIcon from '@mui/icons-material/SmartToyOutlined';
import VerifiedOutlinedIcon from '@mui/icons-material/VerifiedOutlined';
import SettingsOutlinedIcon from '@mui/icons-material/SettingsOutlined';
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined';
import InsertDriveFileOutlinedIcon from '@mui/icons-material/InsertDriveFileOutlined';
import LinkOutlinedIcon from '@mui/icons-material/LinkOutlined';
import ContentCopyOutlinedIcon from '@mui/icons-material/ContentCopyOutlined';
import PushPinIcon from '@mui/icons-material/PushPin';
import PushPinOutlinedIcon from '@mui/icons-material/PushPinOutlined';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import DownloadOutlinedIcon from '@mui/icons-material/DownloadOutlined';
import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import AutoFixHighOutlinedIcon from '@mui/icons-material/AutoFixHighOutlined';
import PersonOutlinedIcon from '@mui/icons-material/PersonOutlined';
import BusinessOutlinedIcon from '@mui/icons-material/BusinessOutlined';
import { formatFileSize } from '../../services/kbFileService';
import { groupForCategory, getFreshness, FRESHNESS_COLORS, isAutoGenerated } from '../../utils/kbConstants';

import AppIcon from '../icons/AppIcon';

function timeAgo(date) {
  if (!date) return '';
  const diff = Date.now() - new Date(date).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;
  return `${Math.floor(days / 30)}mo ago`;
}

/** Short, human-readable snippet for the card body (notes only - keeps it calm). */
function noteSnippet(doc) {
  if (doc.content_type !== 'note' || !doc.content) return null;
  const text = String(doc.content).replace(/[#>*`_-]/g, ' ').replace(/\s+/g, ' ').trim();
  return text ? text.slice(0, 150) : null;
}

// Shared chip styling for a consistent, legible look.
const chipSx = {
  height: 22,
  fontSize: '0.68rem',
  fontWeight: 600,
  borderRadius: 1.5,
  '& .MuiChip-icon': { fontSize: 14, ml: '4px' },
};

function StatChip({ label, value, color }) {
  if (!value && value !== 0) return null;
  return (
    <Box sx={{ display: 'flex', alignItems: 'baseline', gap: 0.4 }}>
      <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '0.66rem' }}>
        {label}
      </Typography>
      <Typography sx={{ fontWeight: 700, fontSize: '0.74rem', color: color || 'text.primary' }}>
        {value}
      </Typography>
    </Box>
  );
}

function FreshnessDot({ dateStr }) {
  const f = getFreshness(dateStr);
  return (
    <Tooltip title={f === 'today' ? 'Today' : f === 'week' ? 'This week' : 'Older'}>
      <Box sx={{ width: 7, height: 7, borderRadius: '50%', bgcolor: FRESHNESS_COLORS[f], flexShrink: 0 }} />
    </Tooltip>
  );
}

function SourceBadge({ source }) {
  const auto = isAutoGenerated(source);
  return (
    <Chip
      size="small"
      icon={
        <AppIcon
          name={auto ? 'AutoFixHighOutlined' : 'PersonOutlined'}
          fallback={auto ? AutoFixHighOutlinedIcon : PersonOutlinedIcon}
          sx={{ fontSize: '13px !important' }}
        />
      }
      label={auto ? 'Auto' : 'Manual'}
      variant="outlined"
      sx={{ ...chipSx, height: 20, fontSize: '0.62rem', color: 'text.secondary' }}
    />
  );
}

function AgentBadge({ name }) {
  if (!name) return null;
  return (
    <Chip
      size="small"
      icon={<AppIcon name="SmartToyOutlined" fallback={SmartToyOutlinedIcon} sx={{ fontSize: '13px !important' }} />}
      label={name}
      sx={{
        ...chipSx,
        bgcolor: (t) => alpha(t.palette.primary.main, 0.1),
        color: 'primary.main',
        maxWidth: 180,
      }}
    />
  );
}

// ── Goals Card Content ───────────────────────────────────────
function GoalCardContent({ doc, theme }) {
  const m = doc.metadata || {};
  return (
    <>
      <Box sx={{ display: 'flex', gap: 0.6, flexWrap: 'wrap', mb: 0.5, alignItems: 'center' }}>
        <Chip
          size="small"
          label={doc.category?.replace('goal-', '') || 'goal'}
          sx={{ ...chipSx, fontWeight: 700, bgcolor: alpha(theme.palette.primary.main, 0.1), color: 'primary.main' }}
        />
        {m.goal_status && <Chip size="small" label={m.goal_status} variant="outlined" sx={chipSx} />}
        <SourceBadge source={doc.source} />
      </Box>
      <Box sx={{ display: 'flex', gap: 1.75, flexWrap: 'wrap', mt: 0.5 }}>
        <StatChip label="Cost" value={m.total_cost != null ? `$${Number(m.total_cost).toFixed(3)}` : null} />
        <StatChip label="Quality" value={m.avg_quality != null ? `${Number(m.avg_quality).toFixed(0)}%` : null} color="success.main" />
        <StatChip label="Phases" value={m.phases_completed} />
        <StatChip label="Iterations" value={m.iterations} />
      </Box>
      {m.deployment_url && (
        <Box sx={{ mt: 0.6 }}>
          <Chip
            size="small"
            label="Live"
            icon={<AppIcon name="OpenInNew" fallback={OpenInNewIcon} sx={{ fontSize: '13px !important' }} />}
            onClick={(e) => {
              e.stopPropagation();
              window.open(m.deployment_url, '_blank');
            }}
            sx={{ ...chipSx, cursor: 'pointer', bgcolor: alpha(theme.palette.success.main, 0.1), color: 'success.main' }}
          />
        </Box>
      )}
    </>
  );
}

// ── Agents Card Content ──────────────────────────────────────
function AgentCardContent({ doc }) {
  const m = doc.metadata || {};
  return (
    <>
      <Box sx={{ display: 'flex', gap: 0.6, flexWrap: 'wrap', mb: 0.5, alignItems: 'center' }}>
        <AgentBadge name={m.agent_name} />
        {m.agent_role && <Chip size="small" label={m.agent_role} variant="outlined" sx={chipSx} />}
        <SourceBadge source={doc.source} />
      </Box>
      <Box sx={{ display: 'flex', gap: 1.75, flexWrap: 'wrap', mt: 0.5 }}>
        <StatChip label="Done" value={m.tasks_completed} color="success.main" />
        <StatChip label="Failed" value={m.tasks_failed} color="error.main" />
        <StatChip label="Quality" value={m.avg_quality != null ? `${Number(m.avg_quality).toFixed(0)}%` : null} />
        <StatChip label="Cost" value={m.cost_usd != null ? `$${Number(m.cost_usd).toFixed(3)}` : null} />
      </Box>
    </>
  );
}

// ── Quality Card Content ─────────────────────────────────────
function QualityCardContent({ doc, theme }) {
  const m = doc.metadata || {};
  const grade =
    m.grade ||
    (doc.tags || [])
      .find((t) => t.startsWith('grade-'))
      ?.replace('grade-', '')
      .toUpperCase();
  const gradeColors = { A: 'success', B: 'info', C: 'warning', D: 'error' };
  const isPromoted = doc.category === 'library_example';
  return (
    <>
      <Box sx={{ display: 'flex', gap: 0.6, flexWrap: 'wrap', mb: 0.5, alignItems: 'center' }}>
        <Chip
          size="small"
          label={doc.category?.replace('_', ' ') || 'quality'}
          sx={{ ...chipSx, bgcolor: alpha(theme.palette.warning.main, 0.1), color: 'warning.main' }}
        />
        {grade && <Chip size="small" label={`Grade ${grade}`} color={gradeColors[grade] || 'default'} sx={{ ...chipSx, fontWeight: 700 }} />}
        {isPromoted && (
          <Chip
            size="small"
            label="Promoted"
            icon={<AppIcon name="VerifiedOutlined" fallback={VerifiedOutlinedIcon} sx={{ fontSize: '13px !important' }} />}
            color="success"
            sx={chipSx}
          />
        )}
        <SourceBadge source={doc.source} />
      </Box>
      <Box sx={{ display: 'flex', gap: 1.75, flexWrap: 'wrap', mt: 0.5 }}>
        <StatChip label="Type" value={m.deliverable_type} />
        <StatChip label="Score" value={m.score != null ? Number(m.score).toFixed(1) : null} />
      </Box>
    </>
  );
}

// ── System Card Content ──────────────────────────────────────
function SystemCardContent({ doc, theme }) {
  return (
    <Box sx={{ display: 'flex', gap: 0.6, flexWrap: 'wrap', alignItems: 'center' }}>
      <Chip
        size="small"
        label="System"
        sx={{ ...chipSx, fontWeight: 700, bgcolor: alpha(theme.palette.error.main, 0.1), color: 'error.main' }}
      />
      <SourceBadge source={doc.source} />
    </Box>
  );
}

// ── General Card Content ─────────────────────────────────────
function GeneralCardContent({ doc }) {
  const typeIcons = {
    note: DescriptionOutlinedIcon,
    file: InsertDriveFileOutlinedIcon,
    link: LinkOutlinedIcon,
    template: ContentCopyOutlinedIcon,
  };
  const TypeIcon = typeIcons[doc.content_type] || DescriptionOutlinedIcon;
  return (
    <>
      <Box sx={{ display: 'flex', gap: 0.6, flexWrap: 'wrap', alignItems: 'center' }}>
        <Chip
          size="small"
          icon={<AppIcon fallback={TypeIcon} sx={{ fontSize: '13px !important' }} />}
          label={doc.content_type || 'note'}
          sx={chipSx}
        />
        {doc.category && doc.category !== 'general' && <Chip size="small" label={doc.category} variant="outlined" sx={chipSx} />}
        {doc.owner_type && doc.owner_type !== 'user' && (
          <Chip size="small" label={`${doc.owner_type}: ${doc.owner_id || ''}`.slice(0, 20)} variant="outlined" sx={chipSx} />
        )}
        <SourceBadge source={doc.source} />
      </Box>
      {doc.content_type === 'file' && (
        <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '0.72rem', mt: 0.5, display: 'block' }}>
          {doc.file_name || 'File'} · {formatFileSize(doc.file_size)}
        </Typography>
      )}
      {doc.content_type === 'link' && (
        <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: '0.72rem', mt: 0.5, display: 'block' }} noWrap>
          {doc.url_meta?.title || doc.url || 'Link'}
        </Typography>
      )}
    </>
  );
}

// ── Group → Renderer map ─────────────────────────────────────
const GROUP_ICONS = {
  Goals: TrackChangesOutlinedIcon,
  Agents: SmartToyOutlinedIcon,
  Quality: VerifiedOutlinedIcon,
  System: SettingsOutlinedIcon,
  General: DescriptionOutlinedIcon,
  Other: DescriptionOutlinedIcon,
};

const CARD_RENDERERS = {
  Goals: GoalCardContent,
  Agents: AgentCardContent,
  Quality: QualityCardContent,
  System: SystemCardContent,
  General: GeneralCardContent,
  Other: GeneralCardContent,
};

function ActionButton({ title, onClick, name, fallback, color = 'text.secondary' }) {
  return (
    <Tooltip title={title}>
      <IconButton
        size="small"
        onClick={onClick}
        sx={{ p: 0.5, color, '&:hover': { bgcolor: (t) => alpha(t.palette.text.primary, 0.06) } }}
      >
        <AppIcon name={name} fallback={fallback} sx={{ fontSize: 17 }} />
      </IconButton>
    </Tooltip>
  );
}

// ── Main Card Component ──────────────────────────────────────
export default function KBCategoryCard({ doc, onEdit, onDelete, onPin, onDownload, onView, orgName }) {
  const theme = useTheme();
  const group = groupForCategory(doc.category);
  // Use the brand primary accent for the card frame (on-brand across all groups);
  // the group is still distinguished by its icon + semantic content chips.
  const color = theme.palette.primary.main;
  const GroupIcon = GROUP_ICONS[group] || GROUP_ICONS.Other;
  const Renderer = CARD_RENDERERS[group] || CARD_RENDERERS.Other;
  const m = doc.metadata || {};
  const snippet = noteSnippet(doc);

  return (
    <Paper
      elevation={0}
      onClick={() => onView?.(doc)}
      sx={{
        p: { xs: 1.75, sm: 2 },
        borderRadius: 3,
        border: '1px solid',
        borderColor: alpha(color, 0.2),
        background: `linear-gradient(150deg, ${alpha(color, 0.06)} 0%, ${alpha(theme.palette.background.paper, 0.98)} 60%)`,
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        transition: 'border-color .18s, transform .18s, box-shadow .18s',
        cursor: onView ? 'pointer' : 'default',
        '& .kb-actions': { opacity: 1, transition: 'opacity .15s' },
        '@media (hover: hover)': {
          '& .kb-actions': { opacity: 0 },
          '&:hover .kb-actions': { opacity: 1 },
        },
        '&:hover': {
          borderColor: alpha(color, 0.45),
          transform: 'translateY(-2px)',
          boxShadow: `0 8px 24px ${alpha(color, 0.14)}`,
        },
      }}
    >
      {/* Header: avatar + title + actions */}
      <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 1.25 }}>
        <Box
          sx={{
            width: 38,
            height: 38,
            borderRadius: 2,
            flexShrink: 0,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background: `linear-gradient(140deg, ${alpha(color, 0.22)} 0%, ${alpha(color, 0.1)} 100%)`,
            border: '1px solid',
            borderColor: alpha(color, 0.18),
          }}
        >
          <AppIcon fallback={GroupIcon} sx={{ fontSize: 20, color }} />
        </Box>

        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.6, mb: 0.25 }}>
            <FreshnessDot dateStr={doc.created_at} />
            <Typography
              variant="subtitle2"
              sx={{
                fontWeight: 700,
                lineHeight: 1.3,
                fontSize: '0.9rem',
                display: '-webkit-box',
                WebkitLineClamp: 2,
                WebkitBoxOrient: 'vertical',
                overflow: 'hidden',
              }}
            >
              {doc.title || 'Untitled'}
            </Typography>
            {doc.is_pinned && (
              <AppIcon name="PushPin" fallback={PushPinIcon} sx={{ fontSize: 15, color: 'warning.main', flexShrink: 0, ml: 'auto' }} />
            )}
          </Box>
        </Box>

        {/* Actions (hover-reveal on desktop, always on touch) */}
        <Box className="kb-actions" onClick={(e) => e.stopPropagation()} sx={{ display: 'flex', gap: 0.25, flexShrink: 0, mt: -0.5, mr: -0.5 }}>
          {onPin && (
            <ActionButton
              title={doc.is_pinned ? 'Unpin' : 'Pin'}
              onClick={() => onPin(doc)}
              name={doc.is_pinned ? 'PushPin' : 'PushPinOutlined'}
              fallback={doc.is_pinned ? PushPinIcon : PushPinOutlinedIcon}
              color={doc.is_pinned ? 'warning.main' : 'text.secondary'}
            />
          )}
          {onDownload && doc.content_type === 'file' && (
            <ActionButton title="Download" onClick={() => onDownload(doc)} name="DownloadOutlined" fallback={DownloadOutlinedIcon} />
          )}
          {onEdit && <ActionButton title="Edit" onClick={() => onEdit(doc)} name="EditOutlined" fallback={EditOutlinedIcon} />}
          {onDelete && (
            <ActionButton title="Delete" onClick={() => onDelete(doc)} name="DeleteOutline" fallback={DeleteOutlineIcon} color="error.main" />
          )}
        </Box>
      </Box>

      {/* Body */}
      <Box sx={{ mt: 1, flex: 1 }}>
        <Renderer doc={doc} theme={theme} />

        {snippet && (
          <Typography
            variant="body2"
            sx={{
              color: 'text.secondary',
              fontSize: '0.78rem',
              lineHeight: 1.45,
              mt: 0.75,
              display: '-webkit-box',
              WebkitLineClamp: 2,
              WebkitBoxOrient: 'vertical',
              overflow: 'hidden',
            }}
          >
            {snippet}
          </Typography>
        )}

        {doc.tags?.length > 0 && (
          <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap', mt: 0.9 }}>
            {doc.tags.slice(0, 4).map((t) => (
              <Chip
                key={t}
                size="small"
                label={`#${t}`}
                variant="outlined"
                sx={{ fontSize: '0.64rem', height: 20, borderRadius: 1, borderColor: alpha(theme.palette.text.primary, 0.14), color: 'text.secondary' }}
              />
            ))}
            {doc.tags.length > 4 && (
              <Typography variant="caption" sx={{ color: 'text.disabled', fontSize: '0.64rem', alignSelf: 'center' }}>
                +{doc.tags.length - 4}
              </Typography>
            )}
          </Box>
        )}
      </Box>

      {/* Footer meta */}
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75, mt: 1.25, pt: 1, borderTop: '1px solid', borderColor: alpha(theme.palette.text.primary, 0.06), flexWrap: 'wrap' }}>
        {group !== 'Agents' && m.agent_name && <AgentBadge name={m.agent_name} />}
        {(orgName || doc.organization_id) && (
          <Chip
            size="small"
            label={orgName || 'Organization'}
            icon={<AppIcon name="BusinessOutlined" fallback={BusinessOutlinedIcon} sx={{ fontSize: '12px !important' }} />}
            variant="outlined"
            sx={{ height: 20, fontSize: '0.62rem', borderRadius: 1, maxWidth: 150 }}
          />
        )}
        {m.goal_id && (
          <Chip
            size="small"
            label="Goal"
            icon={<AppIcon name="TrackChangesOutlined" fallback={TrackChangesOutlinedIcon} sx={{ fontSize: '12px !important' }} />}
            variant="outlined"
            sx={{ height: 20, fontSize: '0.62rem', borderRadius: 1 }}
            onClick={(e) => e.stopPropagation()}
          />
        )}
        <Typography variant="caption" sx={{ color: 'text.disabled', fontSize: '0.7rem', ml: 'auto' }}>
          {timeAgo(doc.created_at)}
        </Typography>
      </Box>
    </Paper>
  );
}
