/**
 * Curated registry of external libraries users can "Import From..." into the
 * Marketplace, keyed by the 6 tab category ids. Each library is a real, public
 * project; its `items` are authored to the per-tab functional schema so that the
 * tab's existing action (Add / Connect / Install / Rent / Use Template / Use)
 * works on an imported item exactly like a built-in one.
 *
 * Per-tab item schema:
 *  - orgs:   { id, name, description, type, industry, entityCount, levels, entities[] }
 *  - teams:  { id, name, description, industry, color, members[], criteria[] }
 *  - agents: { _id, name, role, description, category, capabilities[], connection_type, model, cost_per_task, system_prompt, tools[] }
 *  - models: { id, name, exactModel, provider, hardware, ram, contextLength, pricePerHour, tokensPerSecond, status, sizeClass, description, rating, reviewsCount }
 *  - tools:  { id, name, description, connectionType, status, category }
 *  - skills: { id, slug, name, description, category, tags[], compatible_roles[], content, icon }
 *
 * Plain hyphens only (no em or en dashes). URLs verified as real public sources.
 */

export const MARKETPLACE_IMPORT_SOURCES = {
  // ── ORGANIZATIONS ────────────────────────────────────────────────
  orgs: [
    {
      id: 'holacracy-constitution',
      name: 'Holacracy Constitution',
      description:
        'Self-management operating system that replaces the management hierarchy with nested role circles.',
      url: 'https://www.holacracy.org/constitution',
      author: 'HolacracyOne',
      itemCount: 3,
      tags: ['governance', 'self-management', 'circles'],
      items: [
        {
          id: 'hol-anchor-circle',
          name: 'Anchor Circle Structure',
          type: 'holding',
          industry: 'Self-management',
          description:
            'Top anchor circle holding company purpose, with two operational sub-circles.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Anchor Circle', level: 0, role: 'holding', parentId: null },
            {
              name: 'General Company Circle',
              level: 1,
              role: 'division',
              parentId: 'Anchor Circle',
            },
            { name: 'Operations Circle', level: 1, role: 'division', parentId: 'Anchor Circle' },
          ],
        },
        {
          id: 'hol-go-circle',
          name: 'General Company Circle',
          type: 'division',
          industry: 'Self-management',
          description:
            'Broad working circle that contains the cross-functional roles of a Holacracy org.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'General Company Circle', level: 0, role: 'division', parentId: null },
            {
              name: 'Product Sub-Circle',
              level: 1,
              role: 'department',
              parentId: 'General Company Circle',
            },
            {
              name: 'Marketing Sub-Circle',
              level: 1,
              role: 'department',
              parentId: 'General Company Circle',
            },
          ],
        },
        {
          id: 'hol-role-circle',
          name: 'Role Circle Template',
          type: 'department',
          industry: 'Self-management',
          description:
            'A single circle that breaks a complex role into a lead link plus focused roles.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Lead Link Circle', level: 0, role: 'department', parentId: null },
            { name: 'Rep Link Role', level: 1, role: 'department', parentId: 'Lead Link Circle' },
            {
              name: 'Facilitator Role',
              level: 1,
              role: 'department',
              parentId: 'Lead Link Circle',
            },
          ],
        },
      ],
    },
    {
      id: 'raci-matrix',
      name: 'RACI Responsibility Matrix',
      description:
        'Classic Responsible / Accountable / Consulted / Informed model for mapping ownership across teams.',
      url: 'https://racichart.org/',
      author: 'RACIChart.org',
      itemCount: 3,
      tags: ['raci', 'accountability', 'governance'],
      items: [
        {
          id: 'raci-delivery',
          name: 'Delivery RACI Org',
          type: 'subsidiary',
          industry: 'Operations',
          description:
            'Delivery org split into accountable owner plus responsible execution teams.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Accountable Owner', level: 0, role: 'subsidiary', parentId: null },
            { name: 'Responsible Team', level: 1, role: 'division', parentId: 'Accountable Owner' },
            { name: 'Consulted Team', level: 1, role: 'division', parentId: 'Accountable Owner' },
          ],
        },
        {
          id: 'raci-daci',
          name: 'DACI Decision Org',
          type: 'division',
          industry: 'Operations',
          description:
            'Driver / Approver / Contributor / Informed structure for fast decision making.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Approver', level: 0, role: 'division', parentId: null },
            { name: 'Driver Team', level: 1, role: 'department', parentId: 'Approver' },
            { name: 'Contributor Team', level: 1, role: 'department', parentId: 'Approver' },
          ],
        },
        {
          id: 'raci-program',
          name: 'Program RACI Office',
          type: 'holding',
          industry: 'Operations',
          description: 'Program office with accountable sponsor over responsible workstreams.',
          entityCount: 4,
          levels: 3,
          entities: [
            { name: 'Program Sponsor', level: 0, role: 'holding', parentId: null },
            { name: 'Program Office', level: 1, role: 'subsidiary', parentId: 'Program Sponsor' },
            { name: 'Workstream A', level: 2, role: 'division', parentId: 'Program Office' },
            { name: 'Workstream B', level: 2, role: 'division', parentId: 'Program Office' },
          ],
        },
      ],
    },
    {
      id: 'creately-org-templates',
      name: 'Creately Org Chart Templates',
      description:
        'Ready-made organizational structures from flat startup to matrix and holding group.',
      url: 'https://creately.com/diagram-community/popular/t/org-chart',
      author: 'Creately',
      itemCount: 3,
      tags: ['org-chart', 'templates', 'hierarchy'],
      items: [
        {
          id: 'cre-functional',
          name: 'Functional Hierarchy',
          type: 'subsidiary',
          industry: 'Technology',
          description: 'Departments grouped by function reporting up to the executive team.',
          entityCount: 4,
          levels: 2,
          entities: [
            { name: 'Executive Team', level: 0, role: 'subsidiary', parentId: null },
            { name: 'Engineering', level: 1, role: 'division', parentId: 'Executive Team' },
            { name: 'Sales', level: 1, role: 'division', parentId: 'Executive Team' },
            { name: 'Finance', level: 1, role: 'division', parentId: 'Executive Team' },
          ],
        },
        {
          id: 'cre-matrix',
          name: 'Matrix Organization',
          type: 'division',
          industry: 'Technology',
          description: 'Dual reporting across functional and product lines.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Matrix Leadership', level: 0, role: 'division', parentId: null },
            { name: 'Function Line', level: 1, role: 'department', parentId: 'Matrix Leadership' },
            { name: 'Product Line', level: 1, role: 'department', parentId: 'Matrix Leadership' },
          ],
        },
        {
          id: 'cre-holding',
          name: 'Divisional Holding Group',
          type: 'holding',
          industry: 'Multi-industry',
          description: 'Independent profit-and-loss divisions under a group holding umbrella.',
          entityCount: 4,
          levels: 2,
          entities: [
            { name: 'Group HQ', level: 0, role: 'holding', parentId: null },
            { name: 'Tech Division', level: 1, role: 'subsidiary', parentId: 'Group HQ' },
            { name: 'Retail Division', level: 1, role: 'subsidiary', parentId: 'Group HQ' },
            { name: 'Finance Division', level: 1, role: 'subsidiary', parentId: 'Group HQ' },
          ],
        },
      ],
    },
    {
      id: 'spotify-squad-model',
      name: 'Spotify Squad Model',
      description:
        'Squads, tribes, chapters, and guilds structure that keeps autonomous teams aligned at scale.',
      url: 'https://engineering.atspotify.com/2014/03/spotify-engineering-culture-part-1/',
      author: 'Spotify Engineering',
      itemCount: 4,
      tags: ['squads', 'tribes', 'autonomy'],
      items: [
        {
          id: 'spot-tribe',
          name: 'Tribe of Squads',
          type: 'holding',
          industry: 'Technology',
          description: 'A tribe that groups several autonomous squads around a product area.',
          entityCount: 4,
          levels: 2,
          entities: [
            { name: 'Tribe Lead', level: 0, role: 'holding', parentId: null },
            { name: 'Discovery Squad', level: 1, role: 'division', parentId: 'Tribe Lead' },
            { name: 'Delivery Squad', level: 1, role: 'division', parentId: 'Tribe Lead' },
            { name: 'Platform Squad', level: 1, role: 'division', parentId: 'Tribe Lead' },
          ],
        },
        {
          id: 'spot-squad',
          name: 'Autonomous Squad',
          type: 'division',
          industry: 'Technology',
          description: 'A small self-organizing squad that owns a feature end to end.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Squad', level: 0, role: 'division', parentId: null },
            { name: 'Product Owner Cell', level: 1, role: 'department', parentId: 'Squad' },
            { name: 'Engineering Cell', level: 1, role: 'department', parentId: 'Squad' },
          ],
        },
        {
          id: 'spot-chapter',
          name: 'Chapter and Guild',
          type: 'department',
          industry: 'Technology',
          description: 'Cross-squad chapter and guild that keep craft skills consistent.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Chapter Lead', level: 0, role: 'department', parentId: null },
            { name: 'Chapter Members', level: 1, role: 'department', parentId: 'Chapter Lead' },
            { name: 'Guild', level: 1, role: 'department', parentId: 'Chapter Lead' },
          ],
        },
        {
          id: 'spot-alliance',
          name: 'Tribe Alliance',
          type: 'subsidiary',
          industry: 'Technology',
          description: 'An alliance of tribes coordinating on a shared strategic bet.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Alliance Council', level: 0, role: 'subsidiary', parentId: null },
            { name: 'Growth Tribe', level: 1, role: 'division', parentId: 'Alliance Council' },
            { name: 'Core Tribe', level: 1, role: 'division', parentId: 'Alliance Council' },
          ],
        },
      ],
    },
    {
      id: 'team-topologies',
      name: 'Team Topologies',
      description:
        'Four fundamental team types and three interaction modes for fast flow of change.',
      url: 'https://teamtopologies.com/',
      author: 'Team Topologies',
      itemCount: 4,
      tags: ['team-types', 'flow', 'cognitive-load'],
      items: [
        {
          id: 'tt-stream-aligned',
          name: 'Stream-Aligned Org',
          type: 'holding',
          industry: 'Technology',
          description: 'Stream-aligned teams supported by enabling and platform teams.',
          entityCount: 4,
          levels: 2,
          entities: [
            { name: 'Value Stream', level: 0, role: 'holding', parentId: null },
            { name: 'Stream-Aligned Team', level: 1, role: 'division', parentId: 'Value Stream' },
            { name: 'Enabling Team', level: 1, role: 'division', parentId: 'Value Stream' },
            { name: 'Platform Team', level: 1, role: 'division', parentId: 'Value Stream' },
          ],
        },
        {
          id: 'tt-platform',
          name: 'Platform Team Group',
          type: 'division',
          industry: 'Technology',
          description: 'A platform grouping that provides self-service internal products.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Platform Group', level: 0, role: 'division', parentId: null },
            { name: 'Developer Experience', level: 1, role: 'department', parentId: 'Platform Group' },
            { name: 'Infrastructure', level: 1, role: 'department', parentId: 'Platform Group' },
          ],
        },
        {
          id: 'tt-enabling',
          name: 'Enabling Team Unit',
          type: 'department',
          industry: 'Technology',
          description: 'An enabling team that coaches stream-aligned teams on new capabilities.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Enabling Unit', level: 0, role: 'department', parentId: null },
            { name: 'Coaching Cell', level: 1, role: 'department', parentId: 'Enabling Unit' },
            { name: 'Research Cell', level: 1, role: 'department', parentId: 'Enabling Unit' },
          ],
        },
        {
          id: 'tt-complicated-subsystem',
          name: 'Complicated Subsystem Team',
          type: 'subsidiary',
          industry: 'Technology',
          description: 'A team owning a specialist subsystem that needs deep expertise.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Subsystem Team', level: 0, role: 'subsidiary', parentId: null },
            { name: 'Algorithms Cell', level: 1, role: 'division', parentId: 'Subsystem Team' },
            { name: 'Optimization Cell', level: 1, role: 'division', parentId: 'Subsystem Team' },
          ],
        },
      ],
    },
    {
      id: 'sociocracy-30',
      name: 'Sociocracy 3.0',
      description:
        'Open framework of patterns for collaboration, consent decision making, and nested circles.',
      url: 'https://sociocracy30.org/',
      author: 'Sociocracy 3.0',
      itemCount: 4,
      tags: ['consent', 'circles', 'governance'],
      items: [
        {
          id: 's3-nested-circles',
          name: 'Nested Circles Org',
          type: 'holding',
          industry: 'Governance',
          description: 'A general circle with linked delegate circles under it.',
          entityCount: 4,
          levels: 2,
          entities: [
            { name: 'General Circle', level: 0, role: 'holding', parentId: null },
            { name: 'Operations Circle', level: 1, role: 'division', parentId: 'General Circle' },
            { name: 'Finance Circle', level: 1, role: 'division', parentId: 'General Circle' },
            { name: 'People Circle', level: 1, role: 'division', parentId: 'General Circle' },
          ],
        },
        {
          id: 's3-delegate',
          name: 'Delegate Circle',
          type: 'division',
          industry: 'Governance',
          description: 'A circle that sends delegates to link decisions upward and downward.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Delegate Circle', level: 0, role: 'division', parentId: null },
            { name: 'Delivery Cell', level: 1, role: 'department', parentId: 'Delegate Circle' },
            { name: 'Support Cell', level: 1, role: 'department', parentId: 'Delegate Circle' },
          ],
        },
        {
          id: 's3-helping',
          name: 'Helping Team Circle',
          type: 'department',
          industry: 'Governance',
          description: 'A temporary circle formed to help a domain reach a specific aim.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Helping Circle', level: 0, role: 'department', parentId: null },
            { name: 'Facilitator Role', level: 1, role: 'department', parentId: 'Helping Circle' },
            { name: 'Logbook Keeper', level: 1, role: 'department', parentId: 'Helping Circle' },
          ],
        },
        {
          id: 's3-service',
          name: 'Service Organization',
          type: 'subsidiary',
          industry: 'Governance',
          description: 'A service org linking a mission circle to operational circles.',
          entityCount: 3,
          levels: 2,
          entities: [
            { name: 'Mission Circle', level: 0, role: 'subsidiary', parentId: null },
            { name: 'Value Stream Circle', level: 1, role: 'division', parentId: 'Mission Circle' },
            { name: 'Enabling Circle', level: 1, role: 'division', parentId: 'Mission Circle' },
          ],
        },
      ],
    },
  ],

  // ── CONSILIUM (AI boards / multi-agent crews) ─────────────────────
  teams: [
    {
      id: 'crewai-examples',
      name: 'CrewAI Examples',
      description: 'Official collection of role-playing agent crews for real-world workflows.',
      url: 'https://github.com/crewAIInc/crewAI-examples',
      author: 'crewAIInc',
      itemCount: 3,
      tags: ['crews', 'role-playing', 'orchestration'],
      items: [
        {
          id: 'crew-marketing-strategy',
          name: 'Marketing Strategy Crew',
          industry: 'Marketing',
          color: '#D97706',
          description: 'Researches the market and produces a full marketing campaign plan.',
          members: [
            {
              name: 'Strategy Chair',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 2000,
              resume: 'Leads campaign strategy and sets the brief.',
              skills: ['positioning', 'go-to-market'],
            },
            {
              name: 'Market Researcher',
              role: 'specialist',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.4,
              maxTokens: 1800,
              resume: 'Gathers audience and competitor insight.',
              skills: ['research', 'analysis'],
            },
          ],
          criteria: [
            { name: 'Audience fit', weight: 0.5 },
            { name: 'Channel mix', weight: 0.5 },
          ],
        },
        {
          id: 'crew-landing-page',
          name: 'Landing Page Crew',
          industry: 'Technology',
          color: '#2563EB',
          description: 'Designs and assembles a complete landing page end to end.',
          members: [
            {
              name: 'Build Lead',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.2,
              maxTokens: 2000,
              resume: 'Owns page structure and copy decisions.',
              skills: ['web', 'copy'],
            },
            {
              name: 'Frontend Specialist',
              role: 'specialist',
              provider: 'deepseek',
              model: 'deepseek-chat',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Implements the page components.',
              skills: ['react', 'css'],
            },
          ],
          criteria: [
            { name: 'Conversion clarity', weight: 0.6 },
            { name: 'Performance', weight: 0.4 },
          ],
        },
        {
          id: 'crew-lead-score',
          name: 'Lead Score Flow',
          industry: 'Sales',
          color: '#059669',
          description: 'Qualifies and scores inbound leads with a reviewer in the loop.',
          members: [
            {
              name: 'Scoring Chair',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.2,
              maxTokens: 1600,
              resume: 'Defines scoring rubric and final call.',
              skills: ['sales-ops', 'scoring'],
            },
            {
              name: 'Qualification Auditor',
              role: 'auditor',
              provider: 'openai',
              model: 'gpt-4o-mini',
              temperature: 0.2,
              maxTokens: 1400,
              resume: 'Checks each lead against the rubric.',
              skills: ['audit', 'crm'],
            },
          ],
          criteria: [
            { name: 'Fit score', weight: 0.5 },
            { name: 'Intent signals', weight: 0.5 },
          ],
        },
      ],
    },
    {
      id: 'ag2-autogen',
      name: 'AG2 (formerly AutoGen)',
      description:
        'Open AgentOS with built-in multi-agent conversation patterns: group chat, swarm, nested chat.',
      url: 'https://github.com/ag2ai/ag2',
      author: 'ag2ai',
      itemCount: 3,
      tags: ['conversation', 'group-chat', 'swarm'],
      items: [
        {
          id: 'ag2-group-chat',
          name: 'Group Chat Board',
          industry: 'Technology',
          color: '#7C3AED',
          description:
            'Several agents collaborate in a managed group conversation toward one goal.',
          members: [
            {
              name: 'Group Manager',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 2000,
              resume: 'Routes turns and keeps the group on task.',
              skills: ['orchestration'],
            },
            {
              name: 'Planner',
              role: 'specialist',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.4,
              maxTokens: 1800,
              resume: 'Decomposes the goal into steps.',
              skills: ['planning'],
            },
            {
              name: 'Critic',
              role: 'evaluator',
              provider: 'anthropic',
              model: 'claude-haiku-4-5',
              temperature: 0.2,
              maxTokens: 1600,
              resume: 'Reviews each step for quality.',
              skills: ['review'],
            },
          ],
          criteria: [
            { name: 'Goal completion', weight: 0.6 },
            { name: 'Turn efficiency', weight: 0.4 },
          ],
        },
        {
          id: 'ag2-swarm',
          name: 'Swarm Handoff Board',
          industry: 'Technology',
          color: '#0EA5E9',
          description: 'Handoff-based swarm where agents pass control by capability.',
          members: [
            {
              name: 'Router',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.2,
              maxTokens: 1600,
              resume: 'Decides which specialist handles each step.',
              skills: ['routing'],
            },
            {
              name: 'Domain Specialist',
              role: 'specialist',
              provider: 'deepseek',
              model: 'deepseek-chat',
              temperature: 0.4,
              maxTokens: 1800,
              resume: 'Executes the handed-off task.',
              skills: ['execution'],
            },
          ],
          criteria: [
            { name: 'Handoff accuracy', weight: 0.5 },
            { name: 'Resolution rate', weight: 0.5 },
          ],
        },
        {
          id: 'ag2-hitl',
          name: 'Human-in-the-Loop Board',
          industry: 'Operations',
          color: '#4F46E5',
          description: 'Workflow that pauses for human approval at defined checkpoints.',
          members: [
            {
              name: 'Workflow Chair',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Drives the workflow and requests approvals.',
              skills: ['workflow'],
            },
            {
              name: 'Approval Observer',
              role: 'observer',
              provider: 'openai',
              model: 'gpt-4o-mini',
              temperature: 0.2,
              maxTokens: 1200,
              resume: 'Surfaces checkpoints for human sign-off.',
              skills: ['compliance'],
            },
          ],
          criteria: [
            { name: 'Checkpoint coverage', weight: 0.6 },
            { name: 'Throughput', weight: 0.4 },
          ],
        },
      ],
    },
    {
      id: 'metagpt',
      name: 'MetaGPT',
      description:
        'Multi-agent framework that simulates a software company: PM, architect, engineers, QA.',
      url: 'https://github.com/FoundationAgents/MetaGPT',
      author: 'FoundationAgents',
      itemCount: 3,
      tags: ['software-company', 'sop', 'roles'],
      items: [
        {
          id: 'mg-software-company',
          name: 'Software Company Board',
          industry: 'Technology',
          color: '#2563EB',
          description: 'Turns a one-line requirement into a PRD, design, and implementation plan.',
          members: [
            {
              name: 'Product Manager',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 2000,
              resume: 'Writes the PRD and user stories.',
              skills: ['prd', 'requirements'],
            },
            {
              name: 'Architect',
              role: 'specialist',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.2,
              maxTokens: 2000,
              resume: 'Designs system architecture and APIs.',
              skills: ['architecture'],
            },
            {
              name: 'QA Engineer',
              role: 'auditor',
              provider: 'deepseek',
              model: 'deepseek-chat',
              temperature: 0.2,
              maxTokens: 1600,
              resume: 'Defines and runs the test plan.',
              skills: ['qa', 'testing'],
            },
          ],
          criteria: [
            { name: 'Spec completeness', weight: 0.5 },
            { name: 'Design soundness', weight: 0.5 },
          ],
        },
        {
          id: 'mg-research-team',
          name: 'Research and Design Board',
          industry: 'Technology',
          color: '#7C3AED',
          description: 'Researches a problem space and proposes a design direction.',
          members: [
            {
              name: 'Research Lead',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.4,
              maxTokens: 1800,
              resume: 'Frames the research questions.',
              skills: ['research'],
            },
            {
              name: 'Design Evaluator',
              role: 'evaluator',
              provider: 'anthropic',
              model: 'claude-haiku-4-5',
              temperature: 0.3,
              maxTokens: 1600,
              resume: 'Scores proposed designs.',
              skills: ['evaluation'],
            },
          ],
          criteria: [
            { name: 'Evidence quality', weight: 0.5 },
            { name: 'Design clarity', weight: 0.5 },
          ],
        },
        {
          id: 'mg-data-team',
          name: 'Data Interpreter Board',
          industry: 'Data',
          color: '#DC2626',
          description: 'Plans and runs a data analysis from a natural-language ask.',
          members: [
            {
              name: 'Analysis Chair',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Plans the analysis steps.',
              skills: ['analysis'],
            },
            {
              name: 'Code Specialist',
              role: 'specialist',
              provider: 'deepseek',
              model: 'deepseek-coder',
              temperature: 0.2,
              maxTokens: 2000,
              resume: 'Writes and runs the analysis code.',
              skills: ['python', 'pandas'],
            },
          ],
          criteria: [
            { name: 'Correctness', weight: 0.6 },
            { name: 'Insight value', weight: 0.4 },
          ],
        },
      ],
    },
    {
      id: 'langgraph-examples',
      name: 'LangGraph',
      description:
        'Stateful graph framework for building controllable multi-agent workflows with LangChain.',
      url: 'https://github.com/langchain-ai/langgraph',
      author: 'LangChain AI',
      itemCount: 4,
      tags: ['graph', 'stateful', 'supervisor'],
      items: [
        {
          id: 'lg-supervisor',
          name: 'Supervisor Board',
          industry: 'Technology',
          color: '#1D4ED8',
          description: 'A supervisor node that routes work to specialized worker nodes.',
          members: [
            {
              name: 'Supervisor',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.2,
              maxTokens: 2000,
              resume: 'Decides which worker acts next and when to finish.',
              skills: ['routing', 'orchestration'],
            },
            {
              name: 'Research Worker',
              role: 'specialist',
              provider: 'deepseek',
              model: 'deepseek-chat',
              temperature: 0.4,
              maxTokens: 1800,
              resume: 'Gathers information for the supervisor.',
              skills: ['research'],
            },
          ],
          criteria: [
            { name: 'Routing accuracy', weight: 0.6 },
            { name: 'Task completion', weight: 0.4 },
          ],
        },
        {
          id: 'lg-reflection',
          name: 'Reflection Board',
          industry: 'Technology',
          color: '#7C3AED',
          description: 'A generator and reflector loop that refines output through critique.',
          members: [
            {
              name: 'Generator',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.5,
              maxTokens: 2000,
              resume: 'Produces the initial and revised drafts.',
              skills: ['generation'],
            },
            {
              name: 'Reflector',
              role: 'evaluator',
              provider: 'anthropic',
              model: 'claude-haiku-4-5',
              temperature: 0.2,
              maxTokens: 1600,
              resume: 'Critiques drafts and suggests improvements.',
              skills: ['review', 'evaluation'],
            },
          ],
          criteria: [
            { name: 'Output quality', weight: 0.6 },
            { name: 'Iteration speed', weight: 0.4 },
          ],
        },
        {
          id: 'lg-plan-execute',
          name: 'Plan and Execute Board',
          industry: 'Operations',
          color: '#059669',
          description: 'Plans a multi-step task upfront then executes each step with replanning.',
          members: [
            {
              name: 'Planner',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Builds and updates the step plan.',
              skills: ['planning'],
            },
            {
              name: 'Executor',
              role: 'specialist',
              provider: 'deepseek',
              model: 'deepseek-chat',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Executes each planned step.',
              skills: ['execution'],
            },
            {
              name: 'Replan Auditor',
              role: 'auditor',
              provider: 'openai',
              model: 'gpt-4o-mini',
              temperature: 0.2,
              maxTokens: 1400,
              resume: 'Checks progress and triggers replanning.',
              skills: ['audit'],
            },
          ],
          criteria: [
            { name: 'Plan quality', weight: 0.5 },
            { name: 'Step success rate', weight: 0.5 },
          ],
        },
        {
          id: 'lg-rag-board',
          name: 'Agentic RAG Board',
          industry: 'Data',
          color: '#DC2626',
          description: 'Retrieval agents that grade and rewrite queries before answering.',
          members: [
            {
              name: 'Retrieval Chair',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Coordinates retrieval and answer synthesis.',
              skills: ['rag', 'retrieval'],
            },
            {
              name: 'Relevance Grader',
              role: 'evaluator',
              provider: 'openai',
              model: 'gpt-4o-mini',
              temperature: 0.2,
              maxTokens: 1400,
              resume: 'Grades whether retrieved chunks are relevant.',
              skills: ['grading'],
            },
          ],
          criteria: [
            { name: 'Answer grounding', weight: 0.6 },
            { name: 'Retrieval precision', weight: 0.4 },
          ],
        },
      ],
    },
    {
      id: 'autogen-studio',
      name: 'AutoGen Studio',
      description:
        'Low-code interface from Microsoft for prototyping multi-agent teams and workflows.',
      url: 'https://github.com/microsoft/autogen',
      author: 'Microsoft',
      itemCount: 4,
      tags: ['low-code', 'teams', 'prototyping'],
      items: [
        {
          id: 'ags-roundrobin',
          name: 'Round Robin Team',
          industry: 'Technology',
          color: '#2563EB',
          description: 'Agents take turns in a fixed order until the task is done.',
          members: [
            {
              name: 'Team Lead',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Frames the task and opens the round.',
              skills: ['coordination'],
            },
            {
              name: 'Contributor',
              role: 'specialist',
              provider: 'deepseek',
              model: 'deepseek-chat',
              temperature: 0.4,
              maxTokens: 1600,
              resume: 'Adds work on each turn.',
              skills: ['execution'],
            },
          ],
          criteria: [
            { name: 'Coverage', weight: 0.5 },
            { name: 'Turn efficiency', weight: 0.5 },
          ],
        },
        {
          id: 'ags-selector',
          name: 'Selector Team',
          industry: 'Technology',
          color: '#0EA5E9',
          description: 'A model picks the next speaker based on the conversation state.',
          members: [
            {
              name: 'Selector',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.2,
              maxTokens: 1600,
              resume: 'Chooses who should respond next.',
              skills: ['routing'],
            },
            {
              name: 'Specialist A',
              role: 'specialist',
              provider: 'deepseek',
              model: 'deepseek-chat',
              temperature: 0.4,
              maxTokens: 1600,
              resume: 'Handles domain-specific turns.',
              skills: ['domain'],
            },
          ],
          criteria: [
            { name: 'Selection accuracy', weight: 0.6 },
            { name: 'Resolution rate', weight: 0.4 },
          ],
        },
        {
          id: 'ags-coding',
          name: 'Coding Team',
          industry: 'Technology',
          color: '#059669',
          description: 'A coder and reviewer pair that writes and checks executable code.',
          members: [
            {
              name: 'Coder',
              role: 'chairman',
              provider: 'deepseek',
              model: 'deepseek-coder',
              temperature: 0.2,
              maxTokens: 2000,
              resume: 'Writes and runs the code.',
              skills: ['coding'],
            },
            {
              name: 'Code Reviewer',
              role: 'auditor',
              provider: 'anthropic',
              model: 'claude-haiku-4-5',
              temperature: 0.2,
              maxTokens: 1600,
              resume: 'Reviews the code for correctness.',
              skills: ['review', 'qa'],
            },
          ],
          criteria: [
            { name: 'Correctness', weight: 0.6 },
            { name: 'Readability', weight: 0.4 },
          ],
        },
        {
          id: 'ags-society',
          name: 'Society of Mind Team',
          industry: 'Operations',
          color: '#4F46E5',
          description: 'An inner team wrapped as a single agent within an outer team.',
          members: [
            {
              name: 'Outer Chair',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Coordinates the nested inner team.',
              skills: ['orchestration'],
            },
            {
              name: 'Inner Observer',
              role: 'observer',
              provider: 'openai',
              model: 'gpt-4o-mini',
              temperature: 0.2,
              maxTokens: 1200,
              resume: 'Summarizes the inner team output.',
              skills: ['summary'],
            },
          ],
          criteria: [
            { name: 'Nested coherence', weight: 0.5 },
            { name: 'Outcome quality', weight: 0.5 },
          ],
        },
      ],
    },
    {
      id: 'camel-ai',
      name: 'CAMEL-AI',
      description:
        'Framework for role-playing communicative agents that cooperate to solve tasks.',
      url: 'https://github.com/camel-ai/camel',
      author: 'CAMEL-AI',
      itemCount: 4,
      tags: ['role-playing', 'communicative', 'cooperation'],
      items: [
        {
          id: 'cam-roleplay',
          name: 'Role-Playing Board',
          industry: 'Technology',
          color: '#7C3AED',
          description: 'An assistant and user agent role-play to complete a shared task.',
          members: [
            {
              name: 'Task Chair',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.4,
              maxTokens: 2000,
              resume: 'Assigns roles and frames the shared task.',
              skills: ['role-play'],
            },
            {
              name: 'Assistant Specialist',
              role: 'specialist',
              provider: 'deepseek',
              model: 'deepseek-chat',
              temperature: 0.5,
              maxTokens: 1800,
              resume: 'Plays the assistant role to solve the task.',
              skills: ['execution'],
            },
          ],
          criteria: [
            { name: 'Task completion', weight: 0.6 },
            { name: 'Role fidelity', weight: 0.4 },
          ],
        },
        {
          id: 'cam-workforce',
          name: 'Workforce Board',
          industry: 'Operations',
          color: '#2563EB',
          description: 'A coordinator dispatches subtasks to a workforce of worker agents.',
          members: [
            {
              name: 'Coordinator',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Splits and assigns subtasks.',
              skills: ['coordination'],
            },
            {
              name: 'Worker Specialist',
              role: 'specialist',
              provider: 'deepseek',
              model: 'deepseek-chat',
              temperature: 0.4,
              maxTokens: 1600,
              resume: 'Completes assigned subtasks.',
              skills: ['execution'],
            },
            {
              name: 'Task Auditor',
              role: 'auditor',
              provider: 'openai',
              model: 'gpt-4o-mini',
              temperature: 0.2,
              maxTokens: 1400,
              resume: 'Verifies completed subtasks.',
              skills: ['audit'],
            },
          ],
          criteria: [
            { name: 'Dispatch accuracy', weight: 0.5 },
            { name: 'Completion rate', weight: 0.5 },
          ],
        },
        {
          id: 'cam-critic',
          name: 'Critic-in-Loop Board',
          industry: 'Technology',
          color: '#DC2626',
          description: 'A critic agent selects among candidate proposals each round.',
          members: [
            {
              name: 'Proposal Chair',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.5,
              maxTokens: 1800,
              resume: 'Generates candidate proposals.',
              skills: ['generation'],
            },
            {
              name: 'Critic',
              role: 'evaluator',
              provider: 'anthropic',
              model: 'claude-haiku-4-5',
              temperature: 0.2,
              maxTokens: 1600,
              resume: 'Scores and selects the best proposal.',
              skills: ['evaluation'],
            },
          ],
          criteria: [
            { name: 'Selection quality', weight: 0.6 },
            { name: 'Diversity', weight: 0.4 },
          ],
        },
        {
          id: 'cam-embodied',
          name: 'Embodied Agent Board',
          industry: 'Operations',
          color: '#059669',
          description: 'An agent that plans actions and observes tool results in a loop.',
          members: [
            {
              name: 'Action Planner',
              role: 'chairman',
              provider: 'glm',
              model: 'glm-5.1',
              temperature: 0.3,
              maxTokens: 1800,
              resume: 'Plans the next embodied action.',
              skills: ['planning'],
            },
            {
              name: 'Tool Observer',
              role: 'observer',
              provider: 'openai',
              model: 'gpt-4o-mini',
              temperature: 0.2,
              maxTokens: 1200,
              resume: 'Reports tool results back to the planner.',
              skills: ['observation'],
            },
          ],
          criteria: [
            { name: 'Action success', weight: 0.6 },
            { name: 'Loop efficiency', weight: 0.4 },
          ],
        },
      ],
    },
  ],

  // ── AGENTS ────────────────────────────────────────────────────────
  agents: [
    {
      id: 'openai-agents-sdk',
      name: 'OpenAI Agents SDK Examples',
      description:
        'Official cookbook examples for the OpenAI Agents SDK: handoffs, guardrails, parallel agents.',
      url: 'https://github.com/openai/openai-cookbook/tree/main/examples/agents_sdk',
      author: 'OpenAI',
      itemCount: 3,
      tags: ['agents-sdk', 'handoffs', 'guardrails'],
      items: [
        {
          _id: 'oai-triage',
          name: 'Triage Agent',
          role: 'Triage Agent',
          category: 'Operations',
          description: 'Routes an incoming request to the right specialist agent via handoffs.',
          capabilities: ['Classifies intent', 'Routes to specialists', 'Summarizes context'],
          connection_type: 'openai',
          model: 'gpt-4o-mini',
          cost_per_task: 0.05,
          tools: [],
          system_prompt:
            'You are a triage agent. Read the incoming request, classify its intent, and route it to the most suitable specialist. Pass along a concise summary of the context so the specialist can act immediately.',
        },
        {
          _id: 'oai-guardrail',
          name: 'Guardrail Agent',
          role: 'Guardrail Agent',
          category: 'Operations',
          description: 'Validates inputs and outputs against safety and policy guardrails.',
          capabilities: ['Checks inputs', 'Blocks unsafe output', 'Explains rejections'],
          connection_type: 'openai',
          model: 'gpt-4o-mini',
          cost_per_task: 0.04,
          tools: [],
          system_prompt:
            'You are a guardrail agent. Inspect inputs and outputs against the configured safety and policy rules. Approve compliant content, block anything unsafe, and give a short clear reason for every rejection.',
        },
        {
          _id: 'oai-tool-agent',
          name: 'Tool-Using Agent',
          role: 'Tool-Using Agent',
          category: 'Development',
          description: 'An agent equipped with function tools to act on external systems.',
          capabilities: ['Selects tools', 'Calls functions', 'Handles results'],
          connection_type: 'openai',
          model: 'gpt-4o',
          cost_per_task: 0.12,
          tools: [],
          system_prompt:
            'You are a tool-using agent. Decide which available function tool best advances the task, call it with correct arguments, interpret the result, and continue until the task is complete.',
        },
      ],
    },
    {
      id: 'anthropic-cookbook-agents',
      name: 'Anthropic Cookbook Agents',
      description:
        'Reference implementations of common agent patterns from the official Claude cookbook.',
      url: 'https://github.com/anthropics/claude-cookbooks/tree/main/patterns/agents',
      author: 'Anthropic',
      itemCount: 3,
      tags: ['claude', 'patterns', 'orchestration'],
      items: [
        {
          _id: 'anth-orchestrator',
          name: 'Orchestrator Agent',
          role: 'Orchestrator Agent',
          category: 'Operations',
          description: 'A lead agent that decomposes a task and delegates to worker agents.',
          capabilities: ['Decomposes tasks', 'Delegates work', 'Merges results'],
          connection_type: 'anthropic',
          model: 'claude-sonnet-5',
          cost_per_task: 0.15,
          tools: [],
          system_prompt:
            'You are an orchestrator. Break the objective into well-scoped subtasks, delegate each to the most capable worker, then synthesize their outputs into a single coherent result.',
        },
        {
          _id: 'anth-evaluator',
          name: 'Evaluator-Optimizer Agent',
          role: 'Evaluator-Optimizer Agent',
          category: 'Development',
          description: 'Generates a draft, critiques it, and improves it in a loop.',
          capabilities: ['Drafts solutions', 'Critiques output', 'Iterates to quality'],
          connection_type: 'anthropic',
          model: 'claude-sonnet-5',
          cost_per_task: 0.14,
          tools: [],
          system_prompt:
            'You are an evaluator-optimizer. Produce a draft, then critically review it against the requirements, and revise. Repeat until the output meets the quality bar, then return the final version.',
        },
        {
          _id: 'anth-router',
          name: 'Routing Agent',
          role: 'Routing Agent',
          category: 'Operations',
          description: 'Classifies an input and routes it to a specialized handler.',
          capabilities: ['Classifies input', 'Selects handler', 'Forwards context'],
          connection_type: 'anthropic',
          model: 'claude-haiku-4-5',
          cost_per_task: 0.03,
          tools: [],
          system_prompt:
            'You are a routing agent. Classify each input into one of the known categories and forward it, with relevant context, to the handler that specializes in that category.',
        },
      ],
    },
    {
      id: 'e2b-cookbook',
      name: 'E2B Cookbook',
      description: 'Examples of code-interpreting agents running in isolated E2B cloud sandboxes.',
      url: 'https://github.com/e2b-dev/e2b-cookbook',
      author: 'E2B',
      itemCount: 3,
      tags: ['sandbox', 'code-interpreter', 'data'],
      items: [
        {
          _id: 'e2b-code',
          name: 'Code Interpreter Agent',
          role: 'Code Interpreter Agent',
          category: 'Development',
          description: 'Executes generated Python in a secure sandbox and returns results.',
          capabilities: ['Writes code', 'Runs in sandbox', 'Returns output'],
          connection_type: 'deepseek',
          model: 'deepseek-coder',
          cost_per_task: 0.08,
          tools: [],
          system_prompt:
            'You are a code interpreter agent. Write Python to solve the task, execute it in the secure sandbox, inspect the output or errors, and iterate until you return a correct, verified result.',
        },
        {
          _id: 'e2b-data',
          name: 'Data Analyst Agent',
          role: 'Data Analyst Agent',
          category: 'Operations',
          description: 'Loads data, runs analysis, and renders charts inside a sandbox.',
          capabilities: ['Loads datasets', 'Analyzes data', 'Plots charts'],
          connection_type: 'deepseek',
          model: 'deepseek-chat',
          cost_per_task: 0.09,
          tools: [],
          system_prompt:
            'You are a data analyst agent. Load the provided data, perform the requested analysis in the sandbox, produce clear charts where useful, and summarize the findings in plain language.',
        },
        {
          _id: 'e2b-scraper',
          name: 'Scraper Agent',
          role: 'Scraper Agent',
          category: 'Development',
          description: 'Fetches and processes web content inside an isolated runtime.',
          capabilities: ['Fetches pages', 'Extracts content', 'Structures output'],
          connection_type: 'glm',
          model: 'glm-5.1',
          cost_per_task: 0.06,
          tools: [],
          system_prompt:
            'You are a scraper agent. Fetch the requested web pages in the sandbox, extract the relevant content, and return it as clean structured data, respecting the sites robots and rate limits.',
        },
      ],
    },
    {
      id: 'langchain-templates',
      name: 'LangChain Templates',
      description:
        'Reference application templates and agents from the core LangChain repository.',
      url: 'https://github.com/langchain-ai/langchain',
      author: 'LangChain AI',
      itemCount: 4,
      tags: ['templates', 'chains', 'tools'],
      items: [
        {
          _id: 'lc-sql-agent',
          name: 'SQL Query Agent',
          role: 'SQL Query Agent',
          category: 'Operations',
          description: 'Answers questions by writing and running SQL against a database.',
          capabilities: ['Reads schema', 'Writes SQL', 'Explains results'],
          connection_type: 'deepseek',
          model: 'deepseek-chat',
          cost_per_task: 0.07,
          tools: [],
          system_prompt:
            'You are a SQL query agent. Inspect the database schema, write a correct SQL query for the question, run it, and explain the result in plain language. Never modify data unless explicitly asked.',
        },
        {
          _id: 'lc-web-research',
          name: 'Web Research Agent',
          role: 'Web Research Agent',
          category: 'Marketing',
          description: 'Searches the web and synthesizes a sourced answer.',
          capabilities: ['Searches web', 'Reads sources', 'Cites findings'],
          connection_type: 'glm',
          model: 'glm-5.1',
          cost_per_task: 0.06,
          tools: [],
          system_prompt:
            'You are a web research agent. Search for relevant sources, read them carefully, and produce a concise synthesized answer that cites which source supports each claim.',
        },
        {
          _id: 'lc-extraction',
          name: 'Structured Extraction Agent',
          role: 'Structured Extraction Agent',
          category: 'Operations',
          description: 'Extracts structured fields from unstructured text.',
          capabilities: ['Parses text', 'Fills schema', 'Validates output'],
          connection_type: 'openai',
          model: 'gpt-4o-mini',
          cost_per_task: 0.04,
          tools: [],
          system_prompt:
            'You are a structured extraction agent. Read the input text, extract the requested fields into the target schema, leave missing fields null, and validate that the output conforms to the schema.',
        },
        {
          _id: 'lc-chat-retriever',
          name: 'Conversational Retriever Agent',
          role: 'Conversational Retriever Agent',
          category: 'Development',
          description: 'Chats over a document store with memory of prior turns.',
          capabilities: ['Retrieves context', 'Tracks history', 'Answers grounded'],
          connection_type: 'glm',
          model: 'glm-5.1',
          cost_per_task: 0.05,
          tools: [],
          system_prompt:
            'You are a conversational retriever agent. Use the conversation history to interpret the current question, retrieve relevant context, and answer only from that context, asking for clarification when the question is ambiguous.',
        },
      ],
    },
    {
      id: 'smolagents',
      name: 'smolagents',
      description:
        'Minimal Hugging Face library for agents that write and run code as their actions.',
      url: 'https://github.com/huggingface/smolagents',
      author: 'Hugging Face',
      itemCount: 4,
      tags: ['code-agents', 'minimal', 'tools'],
      items: [
        {
          _id: 'smol-code',
          name: 'Code Action Agent',
          role: 'Code Action Agent',
          category: 'Development',
          description: 'Expresses each action as a short snippet of executable code.',
          capabilities: ['Writes code actions', 'Runs snippets', 'Chains steps'],
          connection_type: 'deepseek',
          model: 'deepseek-coder',
          cost_per_task: 0.06,
          tools: [],
          system_prompt:
            'You are a code action agent. For each step, write a small snippet of Python that performs the action, execute it, observe the output, and continue until the task is solved with a final answer.',
        },
        {
          _id: 'smol-search',
          name: 'Search Tool Agent',
          role: 'Search Tool Agent',
          category: 'Marketing',
          description: 'Uses a web search tool to gather facts before answering.',
          capabilities: ['Calls search tool', 'Reads snippets', 'Summarizes'],
          connection_type: 'glm',
          model: 'glm-5.1',
          cost_per_task: 0.05,
          tools: [],
          system_prompt:
            'You are a search tool agent. Call the web search tool with focused queries, read the returned snippets, and answer the question concisely with the supporting facts.',
        },
        {
          _id: 'smol-vision',
          name: 'Vision Task Agent',
          role: 'Vision Task Agent',
          category: 'Operations',
          description: 'Reasons over images to complete a described visual task.',
          capabilities: ['Reads images', 'Describes content', 'Answers visual questions'],
          connection_type: 'openai',
          model: 'gpt-4o',
          cost_per_task: 0.11,
          tools: [],
          system_prompt:
            'You are a vision task agent. Examine the provided images, describe the relevant details, and answer the visual question accurately, noting when the image does not contain enough information.',
        },
        {
          _id: 'smol-manager',
          name: 'Managed Agents Lead',
          role: 'Managed Agents Lead',
          category: 'Operations',
          description: 'A manager agent that delegates to a set of managed sub-agents.',
          capabilities: ['Plans delegation', 'Calls sub-agents', 'Aggregates results'],
          connection_type: 'glm',
          model: 'glm-5.1',
          cost_per_task: 0.09,
          tools: [],
          system_prompt:
            'You are a managed agents lead. Break the task into parts, delegate each to the most suitable managed sub-agent, collect their results, and combine them into one coherent final answer.',
        },
      ],
    },
    {
      id: 'semantic-kernel',
      name: 'Semantic Kernel',
      description:
        'Microsoft SDK for composing AI agents with plugins, planners, and memory.',
      url: 'https://github.com/microsoft/semantic-kernel',
      author: 'Microsoft',
      itemCount: 4,
      tags: ['plugins', 'planners', 'memory'],
      items: [
        {
          _id: 'sk-planner',
          name: 'Function Planner Agent',
          role: 'Function Planner Agent',
          category: 'Operations',
          description: 'Plans a sequence of plugin functions to reach a goal.',
          capabilities: ['Plans function calls', 'Chains plugins', 'Handles results'],
          connection_type: 'openai',
          model: 'gpt-4o-mini',
          cost_per_task: 0.05,
          tools: [],
          system_prompt:
            'You are a function planner agent. Given a goal and the available plugin functions, produce an ordered plan of function calls, execute it step by step, and adjust the plan if a step fails.',
        },
        {
          _id: 'sk-chat',
          name: 'Chat Completion Agent',
          role: 'Chat Completion Agent',
          category: 'Marketing',
          description: 'A conversational agent that calls plugins when useful.',
          capabilities: ['Holds conversation', 'Invokes plugins', 'Keeps context'],
          connection_type: 'glm',
          model: 'glm-5.1',
          cost_per_task: 0.04,
          tools: [],
          system_prompt:
            'You are a chat completion agent. Converse naturally with the user, invoke plugin functions when they help answer, and keep track of the conversation context across turns.',
        },
        {
          _id: 'sk-memory',
          name: 'Memory Recall Agent',
          role: 'Memory Recall Agent',
          category: 'Development',
          description: 'Stores and recalls facts from a semantic memory store.',
          capabilities: ['Saves memories', 'Recalls context', 'Grounds answers'],
          connection_type: 'deepseek',
          model: 'deepseek-chat',
          cost_per_task: 0.05,
          tools: [],
          system_prompt:
            'You are a memory recall agent. Save durable facts to semantic memory, recall the most relevant ones for each new request, and ground your answers in what you have stored.',
        },
        {
          _id: 'sk-process',
          name: 'Process Orchestration Agent',
          role: 'Process Orchestration Agent',
          category: 'Operations',
          description: 'Runs a stepwise business process across multiple agents.',
          capabilities: ['Drives process steps', 'Coordinates agents', 'Tracks state'],
          connection_type: 'anthropic',
          model: 'claude-haiku-4-5',
          cost_per_task: 0.06,
          tools: [],
          system_prompt:
            'You are a process orchestration agent. Advance the business process one step at a time, coordinate the responsible agents at each step, track the shared state, and report completion or blockers clearly.',
        },
      ],
    },
  ],

  // ── MODELS ──────────────────────────────────────────────────────────
  models: [
    {
      id: 'openrouter-models',
      name: 'OpenRouter Models',
      description: 'Hundreds of hosted models from every major lab, routed through one gateway.',
      url: 'https://openrouter.ai/models',
      author: 'OpenRouter',
      live: true,
      itemCount: 300,
      tags: ['hosted', 'gateway', 'multi-provider'],
      items: [
        {
          id: 'or-anthropic-claude-sonnet-5',
          name: 'Claude Sonnet 4.6',
          exactModel: 'anthropic/claude-sonnet-4-6',
          provider: '@openrouter',
          hardware: 'Hosted (gateway)',
          ram: 'n/a',
          contextLength: 200000,
          pricePerHour: 0,
          tokensPerSecond: null,
          status: 'online',
          sizeClass: 'xl',
          description: 'Hosted model routed via OpenRouter.',
        },
        {
          id: 'or-openai-gpt-4o',
          name: 'GPT-4o',
          exactModel: 'openai/gpt-4o',
          provider: '@openrouter',
          hardware: 'Hosted (gateway)',
          ram: 'n/a',
          contextLength: 128000,
          pricePerHour: 0,
          tokensPerSecond: null,
          status: 'online',
          sizeClass: 'lg',
          description: 'Hosted model routed via OpenRouter.',
        },
      ],
    },
    {
      id: 'ollama-library',
      name: 'Ollama Library',
      description: 'Open models that run locally via a single ollama run command.',
      url: 'https://ollama.com/library',
      author: 'Ollama',
      itemCount: 3,
      tags: ['local', 'open-weight', 'self-hosted'],
      items: [
        {
          id: 'oll-llama3-8b',
          name: 'Llama 3.1 8B',
          exactModel: 'llama3.1:8b-instruct-q8_0',
          provider: '@ollama',
          hardware: '1x RTX 3060 (12GB VRAM)',
          ram: '32GB System RAM',
          contextLength: 131072,
          pricePerHour: 0.12,
          tokensPerSecond: 48,
          status: 'online',
          sizeClass: 'sm',
          description: 'Fast, capable general model for local inference and agent loops.',
          rating: 4.6,
          reviewsCount: 51,
        },
        {
          id: 'oll-qwen3-14b',
          name: 'Qwen 3 14B',
          exactModel: 'qwen3:14b-instruct-q5_K_M',
          provider: '@ollama',
          hardware: '1x RTX 4090 (24GB VRAM)',
          ram: '64GB System RAM',
          contextLength: 32768,
          pricePerHour: 0.22,
          tokensPerSecond: 34,
          status: 'online',
          sizeClass: 'md',
          description: 'Strong reasoning and multilingual model that fits a single high-end GPU.',
          rating: 4.7,
          reviewsCount: 38,
        },
        {
          id: 'oll-deepseek-r1-32b',
          name: 'DeepSeek R1 32B',
          exactModel: 'deepseek-r1:32b-q4_K_M',
          provider: '@ollama',
          hardware: '2x RTX 3090 (48GB VRAM)',
          ram: '128GB System RAM',
          contextLength: 65536,
          pricePerHour: 0.4,
          tokensPerSecond: 20,
          status: 'online',
          sizeClass: 'lg',
          description: 'Open reasoning model with strong chain-of-thought for hard planning.',
          rating: 4.8,
          reviewsCount: 29,
        },
      ],
    },
    {
      id: 'huggingface-hub',
      name: 'Hugging Face Hub',
      description: 'The largest open model hub with millions of models, datasets, and Spaces.',
      url: 'https://huggingface.co/models',
      author: 'Hugging Face',
      itemCount: 3,
      tags: ['hub', 'open-weight', 'gguf'],
      items: [
        {
          id: 'hf-mistral-7b',
          name: 'Mistral 7B Instruct',
          exactModel: 'mistralai/Mistral-7B-Instruct-v0.3',
          provider: '@huggingface',
          hardware: '1x RTX 3060 (12GB VRAM)',
          ram: '32GB System RAM',
          contextLength: 32768,
          pricePerHour: 0.1,
          tokensPerSecond: 52,
          status: 'online',
          sizeClass: 'sm',
          description: 'Efficient open model good for fast, low-cost local inference.',
          rating: 4.5,
          reviewsCount: 64,
        },
        {
          id: 'hf-qwen-72b',
          name: 'Qwen 2.5 72B',
          exactModel: 'Qwen/Qwen2.5-72B-Instruct',
          provider: '@huggingface',
          hardware: '2x A100 (80GB VRAM)',
          ram: '256GB System RAM',
          contextLength: 131072,
          pricePerHour: 1.1,
          tokensPerSecond: 26,
          status: 'busy',
          sizeClass: 'xl',
          description: 'Frontier-class open model for multilingual tasks and structured output.',
          rating: 4.9,
          reviewsCount: 41,
        },
        {
          id: 'hf-gemma-27b',
          name: 'Gemma 2 27B',
          exactModel: 'google/gemma-2-27b-it',
          provider: '@huggingface',
          hardware: '1x A100 (40GB VRAM)',
          ram: '128GB System RAM',
          contextLength: 8192,
          pricePerHour: 0.55,
          tokensPerSecond: 24,
          status: 'online',
          sizeClass: 'lg',
          description: 'Capable lightweight-architecture model from Google for general use.',
          rating: 4.6,
          reviewsCount: 33,
        },
      ],
    },
    {
      id: 'openrouter-model-catalog',
      name: 'OpenRouter Model Catalog',
      description: 'Single API gateway routing to hundreds of hosted models across providers.',
      url: 'https://openrouter.ai/models',
      author: 'OpenRouter',
      itemCount: 3,
      tags: ['gateway', 'hosted', 'multi-provider'],
      items: [
        {
          id: 'or-gemini-flash',
          name: 'Gemini 2.5 Flash',
          exactModel: 'google/gemini-2.5-flash',
          provider: '@openrouter',
          hardware: 'Hosted (gateway)',
          ram: 'n/a',
          contextLength: 1048576,
          pricePerHour: 0.3,
          tokensPerSecond: 120,
          status: 'online',
          sizeClass: 'md',
          description: 'Fast low-cost hosted model for high-volume agent work.',
          rating: 4.7,
          reviewsCount: 88,
        },
        {
          id: 'or-deepseek-v3',
          name: 'DeepSeek V3',
          exactModel: 'deepseek/deepseek-chat',
          provider: '@openrouter',
          hardware: 'Hosted (gateway)',
          ram: 'n/a',
          contextLength: 65536,
          pricePerHour: 0.25,
          tokensPerSecond: 60,
          status: 'online',
          sizeClass: 'lg',
          description: 'Low-cost high-performance hosted reasoning model.',
          rating: 4.8,
          reviewsCount: 72,
        },
        {
          id: 'or-claude-sonnet',
          name: 'Claude Sonnet',
          exactModel: 'anthropic/claude-sonnet-4',
          provider: '@openrouter',
          hardware: 'Hosted (gateway)',
          ram: 'n/a',
          contextLength: 200000,
          pricePerHour: 0.9,
          tokensPerSecond: 45,
          status: 'online',
          sizeClass: 'xl',
          description: 'Strong hosted model for planning and high-quality writing.',
          rating: 4.9,
          reviewsCount: 95,
        },
      ],
    },
    {
      id: 'vllm-models',
      name: 'vLLM',
      description:
        'High-throughput serving engine for running open models locally with paged attention.',
      url: 'https://github.com/vllm-project/vllm',
      author: 'vLLM Project',
      itemCount: 4,
      tags: ['serving', 'throughput', 'self-hosted'],
      items: [
        {
          id: 'vllm-llama3-70b',
          name: 'Llama 3.3 70B',
          exactModel: 'meta-llama/Llama-3.3-70B-Instruct',
          provider: '@vllm',
          hardware: '2x A100 (80GB VRAM)',
          ram: '256GB System RAM',
          contextLength: 131072,
          pricePerHour: 1.2,
          tokensPerSecond: 30,
          status: 'online',
          sizeClass: 'xl',
          description: 'Frontier open model served at high throughput for demanding agent work.',
          rating: 4.8,
          reviewsCount: 47,
        },
        {
          id: 'vllm-qwen-coder-32b',
          name: 'Qwen 2.5 Coder 32B',
          exactModel: 'Qwen/Qwen2.5-Coder-32B-Instruct',
          provider: '@vllm',
          hardware: '2x RTX 4090 (48GB VRAM)',
          ram: '128GB System RAM',
          contextLength: 32768,
          pricePerHour: 0.6,
          tokensPerSecond: 40,
          status: 'online',
          sizeClass: 'lg',
          description: 'Strong open coding model for code generation and review agents.',
          rating: 4.7,
          reviewsCount: 39,
        },
        {
          id: 'vllm-mixtral-8x7b',
          name: 'Mixtral 8x7B',
          exactModel: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
          provider: '@vllm',
          hardware: '2x A100 (80GB VRAM)',
          ram: '256GB System RAM',
          contextLength: 32768,
          pricePerHour: 0.9,
          tokensPerSecond: 55,
          status: 'online',
          sizeClass: 'xl',
          description: 'Sparse mixture-of-experts model balancing quality and speed.',
          rating: 4.6,
          reviewsCount: 34,
        },
        {
          id: 'vllm-phi-4',
          name: 'Phi 4 14B',
          exactModel: 'microsoft/phi-4',
          provider: '@vllm',
          hardware: '1x RTX 4090 (24GB VRAM)',
          ram: '64GB System RAM',
          contextLength: 16384,
          pricePerHour: 0.28,
          tokensPerSecond: 46,
          status: 'online',
          sizeClass: 'md',
          description: 'Compact reasoning-focused model that fits a single high-end GPU.',
          rating: 4.5,
          reviewsCount: 28,
        },
      ],
    },
    {
      id: 'lmstudio-models',
      name: 'LM Studio',
      description:
        'Desktop app and catalog for discovering and running local models with one click.',
      url: 'https://lmstudio.ai/models',
      author: 'LM Studio',
      itemCount: 4,
      tags: ['desktop', 'local', 'gguf'],
      items: [
        {
          id: 'lms-llama3-8b',
          name: 'Llama 3.2 3B',
          exactModel: 'lmstudio-community/Llama-3.2-3B-Instruct-GGUF',
          provider: '@lmstudio',
          hardware: '1x RTX 3050 (8GB VRAM)',
          ram: '16GB System RAM',
          contextLength: 131072,
          pricePerHour: 0.08,
          tokensPerSecond: 62,
          status: 'online',
          sizeClass: 'sm',
          description: 'Tiny fast model for lightweight local agent loops and drafting.',
          rating: 4.4,
          reviewsCount: 57,
        },
        {
          id: 'lms-qwen-coder-7b',
          name: 'Qwen 2.5 Coder 7B',
          exactModel: 'lmstudio-community/Qwen2.5-Coder-7B-Instruct-GGUF',
          provider: '@lmstudio',
          hardware: '1x RTX 3060 (12GB VRAM)',
          ram: '32GB System RAM',
          contextLength: 32768,
          pricePerHour: 0.13,
          tokensPerSecond: 50,
          status: 'online',
          sizeClass: 'sm',
          description: 'Efficient local coding model for code completion agents.',
          rating: 4.6,
          reviewsCount: 44,
        },
        {
          id: 'lms-gemma-9b',
          name: 'Gemma 2 9B',
          exactModel: 'lmstudio-community/gemma-2-9b-it-GGUF',
          provider: '@lmstudio',
          hardware: '1x RTX 3060 (12GB VRAM)',
          ram: '32GB System RAM',
          contextLength: 8192,
          pricePerHour: 0.15,
          tokensPerSecond: 42,
          status: 'online',
          sizeClass: 'md',
          description: 'Balanced general-purpose model for local chat and reasoning.',
          rating: 4.5,
          reviewsCount: 36,
        },
        {
          id: 'lms-phi-3-mini',
          name: 'Phi 3 Mini',
          exactModel: 'lmstudio-community/Phi-3-mini-4k-instruct-GGUF',
          provider: '@lmstudio',
          hardware: '1x RTX 3050 (8GB VRAM)',
          ram: '16GB System RAM',
          contextLength: 4096,
          pricePerHour: 0.07,
          tokensPerSecond: 58,
          status: 'busy',
          sizeClass: 'sm',
          description: 'Very small model for cheap high-volume local classification.',
          rating: 4.3,
          reviewsCount: 31,
        },
      ],
    },
    {
      id: 'together-models',
      name: 'Together AI Models',
      description:
        'Hosted inference platform serving a broad catalog of open models via one API.',
      url: 'https://www.together.ai/models',
      author: 'Together AI',
      itemCount: 4,
      tags: ['hosted', 'open-weight', 'inference'],
      items: [
        {
          id: 'tog-llama-405b',
          name: 'Llama 3.1 405B',
          exactModel: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
          provider: '@together',
          hardware: 'Hosted (cluster)',
          ram: 'n/a',
          contextLength: 131072,
          pricePerHour: 2.4,
          tokensPerSecond: 28,
          status: 'online',
          sizeClass: 'xl',
          description: 'Largest open Llama model for the hardest hosted planning tasks.',
          rating: 4.9,
          reviewsCount: 66,
        },
        {
          id: 'tog-qwen-72b',
          name: 'Qwen 2.5 72B Turbo',
          exactModel: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
          provider: '@together',
          hardware: 'Hosted (cluster)',
          ram: 'n/a',
          contextLength: 131072,
          pricePerHour: 0.85,
          tokensPerSecond: 48,
          status: 'online',
          sizeClass: 'xl',
          description: 'Fast hosted frontier model for multilingual and structured tasks.',
          rating: 4.8,
          reviewsCount: 52,
        },
        {
          id: 'tog-mixtral-8x22b',
          name: 'Mixtral 8x22B',
          exactModel: 'mistralai/Mixtral-8x22B-Instruct-v0.1',
          provider: '@together',
          hardware: 'Hosted (cluster)',
          ram: 'n/a',
          contextLength: 65536,
          pricePerHour: 1.05,
          tokensPerSecond: 44,
          status: 'online',
          sizeClass: 'xl',
          description: 'Large mixture-of-experts model for high-quality hosted reasoning.',
          rating: 4.7,
          reviewsCount: 40,
        },
        {
          id: 'tog-deepseek-r1',
          name: 'DeepSeek R1 Hosted',
          exactModel: 'deepseek-ai/DeepSeek-R1',
          provider: '@together',
          hardware: 'Hosted (cluster)',
          ram: 'n/a',
          contextLength: 65536,
          pricePerHour: 1.3,
          tokensPerSecond: 22,
          status: 'busy',
          sizeClass: 'xl',
          description: 'Hosted open reasoning model with deep chain-of-thought for hard planning.',
          rating: 4.9,
          reviewsCount: 58,
        },
      ],
    },
  ],

  // ── TOOLS (MCP servers / connectors) ──────────────────────────────
  tools: [
    {
      id: 'mcp-official-servers',
      name: 'Official MCP Servers',
      description: 'Reference Model Context Protocol servers maintained by the MCP project.',
      url: 'https://github.com/modelcontextprotocol/servers',
      author: 'modelcontextprotocol',
      itemCount: 3,
      tags: ['mcp', 'official', 'connectors'],
      items: [
        {
          id: 'mcp-filesystem',
          name: 'Filesystem MCP',
          description: 'Secure read and write access to local files and directories.',
          connectionType: 'api',
          status: 'active',
          category: 'mcp',
        },
        {
          id: 'mcp-git',
          name: 'Git MCP',
          description: 'Read, search, and manipulate Git repositories.',
          connectionType: 'api',
          status: 'active',
          category: 'mcp',
        },
        {
          id: 'mcp-fetch',
          name: 'Fetch MCP',
          description: 'Retrieve and convert web content for model consumption.',
          connectionType: 'api',
          status: 'active',
          category: 'mcp',
        },
      ],
    },
    {
      id: 'smithery-registry',
      name: 'Smithery Registry',
      description: 'Registry and hosting platform with thousands of installable MCP servers.',
      url: 'https://smithery.ai/',
      author: 'Smithery',
      itemCount: 3,
      tags: ['mcp', 'registry', 'hosted'],
      items: [
        {
          id: 'smith-github',
          name: 'GitHub Server',
          description: 'Manage repos, issues, and pull requests from an agent.',
          connectionType: 'api',
          status: 'active',
          category: 'dev',
        },
        {
          id: 'smith-postgres',
          name: 'Postgres Server',
          description: 'Query and inspect PostgreSQL databases safely.',
          connectionType: 'api',
          status: 'active',
          category: 'data',
        },
        {
          id: 'smith-brave-search',
          name: 'Brave Search',
          description: 'Web search results for grounding agent answers.',
          connectionType: 'api',
          status: 'active',
          category: 'search',
        },
      ],
    },
    {
      id: 'composio-toolkits',
      name: 'Composio Toolkits',
      description: 'Library of authenticated toolkits exposing thousands of tools for agents.',
      url: 'https://composio.dev/',
      author: 'Composio',
      itemCount: 3,
      tags: ['toolkits', 'integrations', 'saas'],
      items: [
        {
          id: 'comp-gmail',
          name: 'Gmail Toolkit',
          description: 'Send, search, and manage email through Gmail.',
          connectionType: 'composio',
          status: 'active',
          category: 'email',
        },
        {
          id: 'comp-jira',
          name: 'Jira Toolkit',
          description: 'Create and update issues and sprints in Jira.',
          connectionType: 'composio',
          status: 'active',
          category: 'project',
        },
        {
          id: 'comp-stripe',
          name: 'Stripe Toolkit',
          description: 'Manage customers, invoices, and payments.',
          connectionType: 'composio',
          status: 'active',
          category: 'payments',
        },
      ],
    },
    {
      id: 'awesome-mcp-servers',
      name: 'Awesome MCP Servers',
      description:
        'Curated community list of production and experimental Model Context Protocol servers.',
      url: 'https://github.com/punkpeye/awesome-mcp-servers',
      author: 'punkpeye',
      itemCount: 4,
      tags: ['mcp', 'awesome-list', 'community'],
      items: [
        {
          id: 'amcp-slack',
          name: 'Slack MCP',
          description: 'Post messages and read channels in a Slack workspace.',
          connectionType: 'api',
          status: 'active',
          category: 'communication',
        },
        {
          id: 'amcp-notion',
          name: 'Notion MCP',
          description: 'Read and update Notion pages and databases.',
          connectionType: 'api',
          status: 'active',
          category: 'productivity',
        },
        {
          id: 'amcp-puppeteer',
          name: 'Puppeteer MCP',
          description: 'Drive a headless browser to navigate and scrape pages.',
          connectionType: 'api',
          status: 'active',
          category: 'browser',
        },
        {
          id: 'amcp-sqlite',
          name: 'SQLite MCP',
          description: 'Query and manage a local SQLite database.',
          connectionType: 'api',
          status: 'active',
          category: 'data',
        },
      ],
    },
    {
      id: 'zapier-mcp',
      name: 'Zapier MCP',
      description:
        'Exposes thousands of Zapier app actions to agents through a single MCP endpoint.',
      url: 'https://zapier.com/mcp',
      author: 'Zapier',
      itemCount: 4,
      tags: ['mcp', 'automation', 'integrations'],
      items: [
        {
          id: 'zap-google-sheets',
          name: 'Google Sheets Action',
          description: 'Create rows and read data from Google Sheets.',
          connectionType: 'api',
          status: 'active',
          category: 'productivity',
        },
        {
          id: 'zap-hubspot',
          name: 'HubSpot Action',
          description: 'Create and update contacts and deals in HubSpot.',
          connectionType: 'api',
          status: 'active',
          category: 'crm',
        },
        {
          id: 'zap-calendar',
          name: 'Google Calendar Action',
          description: 'Create and list calendar events.',
          connectionType: 'api',
          status: 'active',
          category: 'productivity',
        },
        {
          id: 'zap-trello',
          name: 'Trello Action',
          description: 'Create cards and move them across Trello boards.',
          connectionType: 'api',
          status: 'active',
          category: 'project',
        },
      ],
    },
    {
      id: 'apify-actors',
      name: 'Apify Actors',
      description:
        'Store of ready-made web scraping and automation actors callable from agents.',
      url: 'https://apify.com/store',
      author: 'Apify',
      itemCount: 4,
      tags: ['scraping', 'actors', 'automation'],
      items: [
        {
          id: 'apify-web-scraper',
          name: 'Web Scraper Actor',
          description: 'Crawl websites and extract structured data at scale.',
          connectionType: 'api',
          status: 'active',
          category: 'browser',
        },
        {
          id: 'apify-google-search',
          name: 'Google Search Actor',
          description: 'Fetch Google search results as structured data.',
          connectionType: 'api',
          status: 'active',
          category: 'search',
        },
        {
          id: 'apify-instagram',
          name: 'Instagram Scraper Actor',
          description: 'Collect public profile and post data from Instagram.',
          connectionType: 'api',
          status: 'active',
          category: 'social',
        },
        {
          id: 'apify-contact-info',
          name: 'Contact Info Scraper',
          description: 'Extract emails and phone numbers from a list of pages.',
          connectionType: 'api',
          status: 'active',
          category: 'data',
        },
      ],
    },
  ],

  // ── SKILLS (capability / prompt packs) ────────────────────────────
  skills: [
    {
      id: 'anthropic-skills',
      name: 'Anthropic Agent Skills',
      description:
        'Official Agent Skills: folders of instructions and scripts Claude loads for specialized tasks.',
      url: 'https://github.com/anthropics/skills',
      author: 'Anthropic',
      live: true,
      itemCount: 16,
      tags: ['skills', 'claude', 'documents'],
      items: [
        {
          id: 'skill-docx',
          slug: 'docx-authoring',
          name: 'DOCX Authoring',
          category: 'content',
          description: 'Create and edit well-formatted Microsoft Word documents.',
          tags: ['documents', 'word', 'formatting'],
          compatible_roles: ['all'],
          icon: 'article',
          content:
            '# DOCX Authoring\n\n## Purpose\nProduce clean, well-structured Word documents from content.\n\n## How to apply\n- Use clear heading levels and consistent styles.\n- Keep paragraphs short and scannable.\n- Add tables and lists where they aid comprehension.\n- Finish with a brief summary section.',
        },
        {
          id: 'skill-xlsx',
          slug: 'xlsx-builder',
          name: 'XLSX Builder',
          category: 'data',
          description: 'Build and format Excel spreadsheets with sensible structure.',
          tags: ['spreadsheets', 'excel', 'data'],
          compatible_roles: ['all'],
          icon: 'analytics',
          content:
            '# XLSX Builder\n\n## Purpose\nCreate spreadsheets that are easy to read and maintain.\n\n## How to apply\n- Put one clear header row with concise labels.\n- Use a column per variable and a row per record.\n- Apply number and date formats consistently.\n- Add a totals or summary row where useful.',
        },
        {
          id: 'skill-pdf',
          slug: 'pdf-toolkit',
          name: 'PDF Toolkit',
          category: 'content',
          description: 'Read, fill, and produce PDF documents.',
          tags: ['documents', 'pdf'],
          compatible_roles: ['all'],
          icon: 'description',
          content:
            '# PDF Toolkit\n\n## Purpose\nWork with PDF documents reliably.\n\n## How to apply\n- Extract text and tables before reasoning over a PDF.\n- When filling forms, map each field by its label.\n- Keep the output layout faithful to the source.',
        },
      ],
    },
    {
      id: 'awesome-chatgpt-prompts',
      name: 'Awesome ChatGPT Prompts',
      description: 'Large open library of persona prompts that work across modern LLMs.',
      url: 'https://github.com/f/awesome-chatgpt-prompts',
      author: 'prompts.chat',
      live: true,
      itemCount: 200,
      tags: ['prompts', 'personas', 'community'],
      items: [
        {
          id: 'acp-interviewer',
          slug: 'interviewer-persona',
          name: 'Interviewer Persona',
          category: 'business',
          description: 'Conducts a role-specific interview one question at a time.',
          tags: ['prompt', 'hr', 'interview'],
          compatible_roles: ['all'],
          icon: 'psychology',
          content:
            '# Interviewer Persona\n\n## Purpose\nRun a focused interview for a given role.\n\n## How to apply\n- Ask one question at a time and wait for the answer.\n- Follow up on weak or vague responses.\n- Cover skills, experience, and motivation.\n- End with a short structured assessment.',
        },
        {
          id: 'acp-prompt-generator',
          slug: 'prompt-generator',
          name: 'Prompt Generator',
          category: 'prompt-engineering',
          description: 'Helps craft better prompts from a short brief.',
          tags: ['prompt', 'meta'],
          compatible_roles: ['all'],
          icon: 'psychology',
          content:
            '# Prompt Generator\n\n## Purpose\nTurn a rough brief into a precise, effective prompt.\n\n## How to apply\n- Clarify the goal, audience, and output format.\n- State constraints and examples explicitly.\n- Prefer specific instructions over vague ones.\n- Return the final prompt ready to use.',
        },
        {
          id: 'acp-advertiser',
          slug: 'advertiser-persona',
          name: 'Advertiser Persona',
          category: 'content',
          description: 'Builds an ad campaign concept for a product.',
          tags: ['prompt', 'marketing'],
          compatible_roles: ['all'],
          icon: 'campaign',
          content:
            '# Advertiser Persona\n\n## Purpose\nCreate a campaign concept for a product or service.\n\n## How to apply\n- Define the target audience and key message.\n- Propose a hook, channels, and a call to action.\n- Keep copy concise and benefit-led.',
        },
      ],
    },
    {
      id: 'langchain-hub',
      name: 'LangChain Hub',
      description: 'Searchable repository of community prompts, chains, and agents.',
      url: 'https://smith.langchain.com/hub',
      author: 'LangChain',
      itemCount: 3,
      tags: ['prompts', 'chains', 'rag'],
      items: [
        {
          id: 'lch-rag',
          slug: 'rag-qa-prompt',
          name: 'RAG QA Prompt',
          category: 'data',
          description: 'Standard retrieval-augmented question-answering prompt.',
          tags: ['rag', 'retrieval'],
          compatible_roles: ['all'],
          icon: 'database',
          content:
            '# RAG QA Prompt\n\n## Purpose\nAnswer questions using retrieved context only.\n\n## How to apply\n- Read the retrieved passages before answering.\n- Cite which passage supports each claim.\n- If the context lacks the answer, say so plainly.',
        },
        {
          id: 'lch-react',
          slug: 'react-agent-prompt',
          name: 'ReAct Agent Prompt',
          category: 'prompt-engineering',
          description: 'Reasoning-and-acting prompt for tool-using agents.',
          tags: ['agent', 'reasoning'],
          compatible_roles: ['all'],
          icon: 'psychology',
          content:
            '# ReAct Agent Prompt\n\n## Purpose\nInterleave reasoning with tool actions.\n\n## How to apply\n- Think step by step about the next action.\n- Call a tool, observe the result, then reason again.\n- Stop when the goal is met and give the final answer.',
        },
        {
          id: 'lch-summarize',
          slug: 'summarization-prompt',
          name: 'Summarization Prompt',
          category: 'content',
          description: 'Map-reduce style document summarization prompt.',
          tags: ['summarize'],
          compatible_roles: ['all'],
          icon: 'notes',
          content:
            '# Summarization Prompt\n\n## Purpose\nSummarize long documents faithfully.\n\n## How to apply\n- Summarize each chunk, then combine the summaries.\n- Preserve key facts, figures, and decisions.\n- Keep the final summary tight and ordered.',
        },
      ],
    },
    {
      id: 'cursor-directory',
      name: 'Cursor Directory',
      description:
        'Community directory of rules and prompts that steer AI coding assistants per stack.',
      url: 'https://cursor.directory/',
      author: 'Cursor Directory',
      itemCount: 4,
      tags: ['rules', 'coding', 'community'],
      items: [
        {
          id: 'cur-react-rules',
          name: 'React Best Practices',
          slug: 'react-best-practices',
          category: 'development',
          description: 'Guidance for writing clean, modern React components.',
          tags: ['react', 'frontend'],
          compatible_roles: ['specialist'],
          icon: 'code',
          content:
            '# React Best Practices\n\n## Purpose\nWrite maintainable modern React.\n\n## How to apply\n- Prefer function components and hooks.\n- Keep components small and single-purpose.\n- Lift state only as high as needed.\n- Memoize expensive work deliberately.',
        },
        {
          id: 'cur-python-rules',
          name: 'Python Clean Code',
          slug: 'python-clean-code',
          category: 'development',
          description: 'Conventions for readable, testable Python.',
          tags: ['python', 'backend'],
          compatible_roles: ['specialist'],
          icon: 'code',
          content:
            '# Python Clean Code\n\n## Purpose\nWrite Python that is easy to read and test.\n\n## How to apply\n- Follow PEP 8 and use type hints.\n- Keep functions short and pure where possible.\n- Handle errors explicitly, not silently.\n- Add docstrings to public functions.',
        },
        {
          id: 'cur-node-rules',
          name: 'Node API Conventions',
          slug: 'node-api-conventions',
          category: 'development',
          description: 'Patterns for building robust Node.js APIs.',
          tags: ['node', 'api'],
          compatible_roles: ['specialist'],
          icon: 'code',
          content:
            '# Node API Conventions\n\n## Purpose\nBuild robust Node.js APIs.\n\n## How to apply\n- Validate every request body before use.\n- Return consistent error shapes.\n- Keep handlers thin and push logic into services.\n- Never leak secrets in responses.',
        },
        {
          id: 'cur-sql-rules',
          name: 'SQL Query Guidelines',
          slug: 'sql-query-guidelines',
          category: 'data',
          description: 'Guidelines for writing safe, efficient SQL.',
          tags: ['sql', 'database'],
          compatible_roles: ['specialist'],
          icon: 'database',
          content:
            '# SQL Query Guidelines\n\n## Purpose\nWrite safe and efficient SQL.\n\n## How to apply\n- Select only the columns you need.\n- Use parameterized queries, never string concatenation.\n- Add indexes for common filters and joins.\n- Test queries against realistic data volumes.',
        },
      ],
    },
    {
      id: 'prompting-guide',
      name: 'Prompt Engineering Guide',
      description:
        'Open guide of prompting techniques from zero-shot to chain-of-thought and beyond.',
      url: 'https://www.promptingguide.ai/',
      author: 'DAIR.AI',
      itemCount: 4,
      tags: ['prompts', 'techniques', 'reasoning'],
      items: [
        {
          id: 'pg-few-shot',
          name: 'Few-Shot Prompting',
          slug: 'few-shot-prompting',
          category: 'prompt-engineering',
          description: 'Guide the model with a few worked examples.',
          tags: ['few-shot', 'examples'],
          compatible_roles: ['all'],
          icon: 'psychology',
          content:
            '# Few-Shot Prompting\n\n## Purpose\nSteer output format and style with examples.\n\n## How to apply\n- Provide two to five clear input-output examples.\n- Keep the examples consistent in format.\n- Place the real input after the examples.\n- Match example difficulty to the task.',
        },
        {
          id: 'pg-cot',
          name: 'Chain of Thought',
          slug: 'chain-of-thought',
          category: 'prompt-engineering',
          description: 'Ask the model to reason step by step before answering.',
          tags: ['reasoning', 'cot'],
          compatible_roles: ['all'],
          icon: 'psychology',
          content:
            '# Chain of Thought\n\n## Purpose\nImprove reasoning on multi-step problems.\n\n## How to apply\n- Ask the model to think step by step.\n- Have it show intermediate reasoning.\n- Request the final answer on its own line.\n- Verify each step for logical soundness.',
        },
        {
          id: 'pg-self-consistency',
          name: 'Self-Consistency',
          slug: 'self-consistency',
          category: 'prompt-engineering',
          description: 'Sample several reasoning paths and take the majority answer.',
          tags: ['reasoning', 'sampling'],
          compatible_roles: ['all'],
          icon: 'psychology',
          content:
            '# Self-Consistency\n\n## Purpose\nRaise accuracy on reasoning tasks.\n\n## How to apply\n- Generate several independent reasoning paths.\n- Extract the final answer from each path.\n- Pick the answer that appears most often.\n- Prefer this for math and logic questions.',
        },
        {
          id: 'pg-react',
          name: 'ReAct Prompting',
          slug: 'react-prompting',
          category: 'prompt-engineering',
          description: 'Interleave reasoning traces with tool actions.',
          tags: ['agent', 'tools'],
          compatible_roles: ['all'],
          icon: 'psychology',
          content:
            '# ReAct Prompting\n\n## Purpose\nCombine reasoning with acting on tools.\n\n## How to apply\n- Alternate a thought with a concrete action.\n- Observe each action result before continuing.\n- Stop once the goal is reached.\n- Keep thoughts brief and action-focused.',
        },
      ],
    },
    {
      id: 'anthropic-prompt-library',
      name: 'Anthropic Prompt Library',
      description:
        'Official library of ready-to-use prompts for common business and creative tasks.',
      url: 'https://docs.anthropic.com/en/resources/prompt-library/library',
      author: 'Anthropic',
      itemCount: 4,
      tags: ['prompts', 'claude', 'business'],
      items: [
        {
          id: 'apl-code-consultant',
          name: 'Code Consultant',
          slug: 'code-consultant',
          category: 'development',
          description: 'Suggests improvements to a snippet of code.',
          tags: ['code', 'review'],
          compatible_roles: ['specialist'],
          icon: 'code',
          content:
            '# Code Consultant\n\n## Purpose\nImprove a given piece of code.\n\n## How to apply\n- Read the code and its intent first.\n- Point out correctness and clarity issues.\n- Suggest concrete, minimal improvements.\n- Explain why each change helps.',
        },
        {
          id: 'apl-meeting-scribe',
          name: 'Meeting Scribe',
          slug: 'meeting-scribe',
          category: 'business',
          description: 'Turns raw meeting notes into a clean summary with actions.',
          tags: ['meetings', 'summary'],
          compatible_roles: ['all'],
          icon: 'notes',
          content:
            '# Meeting Scribe\n\n## Purpose\nSummarize meeting notes clearly.\n\n## How to apply\n- Extract key decisions and open questions.\n- List action items with owners.\n- Keep the summary short and scannable.\n- Preserve any deadlines mentioned.',
        },
        {
          id: 'apl-grammar-corrector',
          name: 'Grammar Corrector',
          slug: 'grammar-corrector',
          category: 'content',
          description: 'Fixes grammar and spelling while keeping the voice.',
          tags: ['writing', 'editing'],
          compatible_roles: ['all'],
          icon: 'article',
          content:
            '# Grammar Corrector\n\n## Purpose\nCorrect writing without changing meaning.\n\n## How to apply\n- Fix grammar, spelling, and punctuation.\n- Preserve the original tone and voice.\n- Do not add new content.\n- Return only the corrected text.',
        },
        {
          id: 'apl-data-organizer',
          name: 'Data Organizer',
          slug: 'data-organizer',
          category: 'data',
          description: 'Structures messy text into a clean table or list.',
          tags: ['data', 'formatting'],
          compatible_roles: ['all'],
          icon: 'analytics',
          content:
            '# Data Organizer\n\n## Purpose\nTurn unstructured text into clean data.\n\n## How to apply\n- Identify the entities and their attributes.\n- Choose a table or list that fits the data.\n- Keep one record per row and one field per column.\n- Flag any ambiguous or missing values.',
        },
      ],
    },
  ],
};

export function getLibrariesForCategory(category) {
  return MARKETPLACE_IMPORT_SOURCES[category] || [];
}

/**
 * Stable key for a single importable item across all six category schemas
 * (models/tools/orgs/teams use `id`, agents use `_id`, skills use `id`/`slug`).
 * Used for per-item selection and imported-state dedupe in the Import dialog
 * and useImportedLibraries.
 */
export function itemKey(item) {
  return item?.id ?? item?._id ?? item?.slug ?? item?.name ?? '';
}
