/**
 * Predefined list of models available for renting.
 */
export const RENTABLE_MODELS = [
  {
    id: 'model-qwen25-72b',
    name: 'Qwen 2.5 72B',
    exactModel: 'Qwen2.5-72B-Instruct-Q8_0',
    provider: '@cluster_ops',
    hardware: '2x RTX 3090 (48GB VRAM)',
    ram: '128GB System RAM',
    contextLength: 32768,
    pricePerHour: 0.32,
    tokensPerSecond: 22,
    status: 'online',
    sizeClass: 'xl',
    description:
      'Outstanding performance on multi-lingual tasks, coding assistance, and structured JSON output. Excellent quantization quality.',
    rating: 4.9,
    reviewsCount: 34,
  },
  {
    id: 'model-llama31-70b',
    name: 'Llama 3.1 70B',
    exactModel: 'Meta-Llama-3.1-70B-Instruct-Q4_K_M',
    provider: '@gpu_miner_99',
    hardware: '1x RTX 4090 (24GB VRAM)',
    ram: '64GB System RAM',
    contextLength: 8192,
    pricePerHour: 0.18,
    tokensPerSecond: 19,
    status: 'online',
    sizeClass: 'xl',
    description:
      'State-of-the-art open weights model for complex logic, multi-turn instruction following, and reasoning.',
    rating: 4.8,
    reviewsCount: 22,
  },
  {
    id: 'model-deepseek-33b',
    name: 'DeepSeek Coder 33B',
    exactModel: 'DeepSeek-Coder-33B-Instruct-FP16',
    provider: '@deep_coder',
    hardware: '1x A100 PCIe (80GB VRAM)',
    ram: '256GB Server RAM',
    contextLength: 16384,
    pricePerHour: 0.6,
    tokensPerSecond: 38,
    status: 'busy',
    sizeClass: 'lg',
    description:
      'Exceptional coding model with FP16 precision. Ideal for repository-wide refactoring and complex code generation tasks.',
    rating: 4.9,
    reviewsCount: 41,
  },
  {
    id: 'model-mistral-nemo-12b',
    name: 'Mistral Nemo 12B',
    exactModel: 'Mistral-Nemo-12B-Instruct-2407-Q8_0',
    provider: '@homelab_wizard',
    hardware: 'Mac Studio M2 Max (64GB Unified)',
    ram: '64GB Unified Memory',
    contextLength: 128000,
    pricePerHour: 0.08,
    tokensPerSecond: 28,
    status: 'online',
    sizeClass: 'sm',
    description:
      'Massive 128k context window support. Excellent for processing large document lists or long chat transcripts on unified memory.',
    rating: 4.6,
    reviewsCount: 15,
  },
  {
    id: 'model-phi3-medium-14b',
    name: 'Phi-3 Medium 14B',
    exactModel: 'Phi-3-medium-128k-instruct-Q6_K',
    provider: '@edge_dev_pool',
    hardware: '1x RTX 4070 Ti (12GB VRAM)',
    ram: '32GB System RAM',
    contextLength: 128000,
    pricePerHour: 0.1,
    tokensPerSecond: 32,
    status: 'online',
    sizeClass: 'md',
    description:
      'Highly lightweight and optimized model by Microsoft. Excellent reasoning capabilities relative to its compact parameters count.',
    rating: 4.5,
    reviewsCount: 9,
  },
  {
    id: 'model-command-r-plus',
    name: 'Command R+',
    exactModel: 'c4ai-command-r-plus-Q4_K_M-104B',
    provider: '@enterprise_node',
    hardware: '4x RTX 3090 (96GB VRAM total)',
    ram: '256GB System RAM',
    contextLength: 128000,
    pricePerHour: 0.95,
    tokensPerSecond: 14,
    status: 'offline',
    sizeClass: 'xl',
    description:
      'Enterprise-grade model optimized for Retrieval-Augmented Generation (RAG) and multi-step tool use workflows.',
    rating: 4.7,
    reviewsCount: 18,
  },
];
