'use client';

/**
 * PRDTab Component
 * 
 * Displays a Product Requirements Document (PRD) generated from analysis results.
 * Automatically generates the PRD when the component mounts if analysis is complete.
 */

import React, { useState, useEffect, useCallback } from 'react';
import { generatePRD, PRDData, OperationalPRD, TechnicalPRD } from '@/lib/api/prd';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { LoadingSpinner } from '@/components/loading-spinner';
import { AlertCircle, CheckCircle, RefreshCw } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Skeleton } from '@/components/ui/skeleton';
import { cn } from '@/lib/utils';

interface PRDTabProps {
  analysisId: string;
  isAnalysisComplete?: boolean;
}

export function PRDTab({ analysisId, isAnalysisComplete = true }: PRDTabProps) {
  const [prdData, setPrdData] = useState<PRDData | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'operational' | 'technical'>('operational');
  const [autoGenerated, setAutoGenerated] = useState<boolean>(false);

  // Function to generate PRD
  const fetchPRD = useCallback(async () => {
    if (!analysisId) return;
    
    setLoading(true);
    setError(null);
    
    try {
      const response = await generatePRD(analysisId, 'both');
      setPrdData(response.prd_data);
      setAutoGenerated(true);
    } catch (err) {
      console.error('Error generating PRD:', err);
      setError('Failed to generate PRD. Please try again.');
    } finally {
      setLoading(false);
    }
  }, [analysisId]);

  // Auto-generate PRD when component mounts if analysis is complete
  useEffect(() => {
    if (isAnalysisComplete && analysisId && !prdData && !loading && !autoGenerated) {
      fetchPRD();
    }
  }, [isAnalysisComplete, analysisId, prdData, loading, fetchPRD, autoGenerated]);

  // Handle tab change
  const handleTabChange = (value: string) => {
    setActiveTab(value as 'operational' | 'technical');
  };

  // Render loading state
  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-12">
        <LoadingSpinner size="lg" />
        <p className="mt-4 text-muted-foreground">Generating PRD from analysis results...</p>
      </div>
    );
  }

  // Render error state
  if (error) {
    return (
      <Alert variant="destructive" className="mb-6">
        <AlertCircle className="h-4 w-4" />
        <AlertTitle>Error</AlertTitle>
        <AlertDescription>
          {error}
          <Button 
            variant="outline" 
            size="sm" 
            onClick={fetchPRD} 
            className="ml-2"
          >
            <RefreshCw className="mr-2 h-4 w-4" />
            Try Again
          </Button>
        </AlertDescription>
      </Alert>
    );
  }

  // Render empty state
  if (!prdData) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Product Requirements Document</CardTitle>
          <CardDescription>
            Generate a PRD based on the analysis results
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center justify-center py-8">
          <p className="text-muted-foreground mb-4">No PRD has been generated yet.</p>
          <Button onClick={fetchPRD} disabled={!isAnalysisComplete}>
            Generate PRD
          </Button>
          {!isAnalysisComplete && (
            <p className="text-sm text-muted-foreground mt-2">
              Analysis must be complete before generating a PRD.
            </p>
          )}
        </CardContent>
      </Card>
    );
  }

  // Determine which tabs to show
  const hasOperationalPRD = !!prdData.operational_prd;
  const hasTechnicalPRD = !!prdData.technical_prd;

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Product Requirements Document</CardTitle>
              <CardDescription>
                Generated from analysis results
              </CardDescription>
            </div>
            <Button 
              variant="outline" 
              size="sm" 
              onClick={fetchPRD}
              className="flex items-center"
            >
              <RefreshCw className="mr-2 h-4 w-4" />
              Regenerate
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {/* PRD Metadata */}
          {prdData.metadata && (
            <div className="flex flex-wrap gap-2 mb-4">
              <Badge variant="outline" className="bg-primary/10">
                {prdData.metadata.themes_count} Themes
              </Badge>
              <Badge variant="outline" className="bg-primary/10">
                {prdData.metadata.patterns_count} Patterns
              </Badge>
              <Badge variant="outline" className="bg-primary/10">
                {prdData.metadata.insights_count} Insights
              </Badge>
              <Badge variant="outline" className="bg-primary/10">
                {prdData.metadata.personas_count} Personas
              </Badge>
              {prdData.metadata.industry && (
                <Badge variant="outline" className="bg-primary/10">
                  Industry: {prdData.metadata.industry}
                </Badge>
              )}
            </div>
          )}

          {/* PRD Tabs */}
          <Tabs 
            defaultValue={hasOperationalPRD ? 'operational' : 'technical'} 
            value={activeTab}
            onValueChange={handleTabChange}
            className="w-full"
          >
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger 
                value="operational" 
                disabled={!hasOperationalPRD}
              >
                Operational PRD
              </TabsTrigger>
              <TabsTrigger 
                value="technical" 
                disabled={!hasTechnicalPRD}
              >
                Technical PRD
              </TabsTrigger>
            </TabsList>

            {/* Operational PRD Content */}
            {hasOperationalPRD && (
              <TabsContent value="operational" className="mt-6">
                <OperationalPRDContent prd={prdData.operational_prd!} />
              </TabsContent>
            )}

            {/* Technical PRD Content */}
            {hasTechnicalPRD && (
              <TabsContent value="technical" className="mt-6">
                <TechnicalPRDContent prd={prdData.technical_prd!} />
              </TabsContent>
            )}
          </Tabs>
        </CardContent>
      </Card>
    </div>
  );
}

// Component for displaying the Operational PRD content
function OperationalPRDContent({ prd }: { prd: OperationalPRD }) {
  return (
    <div className="space-y-8">
      {/* Objectives Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Objectives</h3>
        <div className="space-y-4">
          {prd.objectives.map((objective, index) => (
            <Card key={index}>
              <CardHeader className="py-3">
                <CardTitle className="text-base">{objective.title}</CardTitle>
              </CardHeader>
              <CardContent className="py-2">
                <p>{objective.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Scope Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Scope</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card>
            <CardHeader className="py-3">
              <CardTitle className="text-base">Included</CardTitle>
            </CardHeader>
            <CardContent className="py-2">
              <ul className="list-disc pl-5 space-y-1">
                {prd.scope.included.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="py-3">
              <CardTitle className="text-base">Excluded</CardTitle>
            </CardHeader>
            <CardContent className="py-2">
              <ul className="list-disc pl-5 space-y-1">
                {prd.scope.excluded.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* User Stories Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">User Stories</h3>
        <Accordion type="multiple" className="space-y-2">
          {prd.user_stories.map((story, index) => (
            <AccordionItem key={index} value={`story-${index}`} className="border rounded-md">
              <AccordionTrigger className="px-4 py-2 hover:no-underline">
                <span className="text-left">{story.story}</span>
              </AccordionTrigger>
              <AccordionContent className="px-4 pb-3">
                <div className="space-y-4">
                  <div>
                    <h4 className="font-medium mb-2">Acceptance Criteria</h4>
                    <ul className="list-disc pl-5 space-y-1">
                      {story.acceptance_criteria.map((criteria, idx) => (
                        <li key={idx}>{criteria}</li>
                      ))}
                    </ul>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div>
                      <h4 className="font-medium mb-2">What</h4>
                      <p className="text-sm">{story.what}</p>
                    </div>
                    <div>
                      <h4 className="font-medium mb-2">Why</h4>
                      <p className="text-sm">{story.why}</p>
                    </div>
                    <div>
                      <h4 className="font-medium mb-2">How</h4>
                      <p className="text-sm">{story.how}</p>
                    </div>
                  </div>
                </div>
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </section>

      {/* Requirements Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Requirements</h3>
        <Accordion type="multiple" className="space-y-2">
          {prd.requirements.map((req, index) => (
            <AccordionItem key={index} value={`req-${index}`} className="border rounded-md">
              <AccordionTrigger className="px-4 py-2 hover:no-underline">
                <div className="flex items-center justify-between w-full">
                  <span className="text-left">
                    <span className="font-medium">{req.id}:</span> {req.title}
                  </span>
                  <Badge className={cn(
                    "ml-2",
                    req.priority === 'High' ? "bg-destructive text-destructive-foreground" : 
                    req.priority === 'Medium' ? "bg-amber-500 text-white" : 
                    "bg-green-500 text-white"
                  )}>
                    {req.priority}
                  </Badge>
                </div>
              </AccordionTrigger>
              <AccordionContent className="px-4 pb-3">
                <p className="mb-3">{req.description}</p>
                {req.related_user_stories && req.related_user_stories.length > 0 && (
                  <div>
                    <h4 className="font-medium mb-1">Related User Stories</h4>
                    <div className="flex flex-wrap gap-1">
                      {req.related_user_stories.map((storyId, idx) => (
                        <Badge key={idx} variant="outline">{storyId}</Badge>
                      ))}
                    </div>
                  </div>
                )}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </section>

      {/* Success Metrics Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Success Metrics</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {prd.success_metrics.map((metric, index) => (
            <Card key={index}>
              <CardHeader className="py-3">
                <CardTitle className="text-base">{metric.metric}</CardTitle>
              </CardHeader>
              <CardContent className="py-2 space-y-2">
                <div>
                  <h4 className="font-medium text-sm">Target</h4>
                  <p className="text-sm">{metric.target}</p>
                </div>
                <div>
                  <h4 className="font-medium text-sm">Measurement Method</h4>
                  <p className="text-sm">{metric.measurement_method}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>
    </div>
  );
}

// Component for displaying the Technical PRD content
function TechnicalPRDContent({ prd }: { prd: TechnicalPRD }) {
  return (
    <div className="space-y-8">
      {/* Objectives Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Technical Objectives</h3>
        <div className="space-y-4">
          {prd.objectives.map((objective, index) => (
            <Card key={index}>
              <CardHeader className="py-3">
                <CardTitle className="text-base">{objective.title}</CardTitle>
              </CardHeader>
              <CardContent className="py-2">
                <p>{objective.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Scope Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Technical Scope</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card>
            <CardHeader className="py-3">
              <CardTitle className="text-base">Included</CardTitle>
            </CardHeader>
            <CardContent className="py-2">
              <ul className="list-disc pl-5 space-y-1">
                {prd.scope.included.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="py-3">
              <CardTitle className="text-base">Excluded</CardTitle>
            </CardHeader>
            <CardContent className="py-2">
              <ul className="list-disc pl-5 space-y-1">
                {prd.scope.excluded.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Architecture Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Architecture</h3>
        <Card className="mb-4">
          <CardHeader className="py-3">
            <CardTitle className="text-base">Overview</CardTitle>
          </CardHeader>
          <CardContent className="py-2">
            <p>{prd.architecture.overview}</p>
          </CardContent>
        </Card>

        <h4 className="font-medium mb-3">Components</h4>
        <Accordion type="multiple" className="space-y-2 mb-4">
          {prd.architecture.components.map((component, index) => (
            <AccordionItem key={index} value={`component-${index}`} className="border rounded-md">
              <AccordionTrigger className="px-4 py-2 hover:no-underline">
                <span className="text-left font-medium">{component.name}</span>
              </AccordionTrigger>
              <AccordionContent className="px-4 pb-3">
                <div className="space-y-3">
                  <div>
                    <h5 className="font-medium text-sm">Purpose</h5>
                    <p>{component.purpose}</p>
                  </div>
                  <div>
                    <h5 className="font-medium text-sm">Interactions</h5>
                    <ul className="list-disc pl-5 space-y-1">
                      {component.interactions.map((interaction, idx) => (
                        <li key={idx}>{interaction}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>

        <Card>
          <CardHeader className="py-3">
            <CardTitle className="text-base">Data Flow</CardTitle>
          </CardHeader>
          <CardContent className="py-2">
            <p>{prd.architecture.data_flow}</p>
          </CardContent>
        </Card>
      </section>

      {/* Implementation Requirements Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Implementation Requirements</h3>
        <Accordion type="multiple" className="space-y-2">
          {prd.implementation_requirements.map((req, index) => (
            <AccordionItem key={index} value={`impl-req-${index}`} className="border rounded-md">
              <AccordionTrigger className="px-4 py-2 hover:no-underline">
                <div className="flex items-center justify-between w-full">
                  <span className="text-left">
                    <span className="font-medium">{req.id}:</span> {req.title}
                  </span>
                  <Badge className={cn(
                    "ml-2",
                    req.priority === 'High' ? "bg-destructive text-destructive-foreground" : 
                    req.priority === 'Medium' ? "bg-amber-500 text-white" : 
                    "bg-green-500 text-white"
                  )}>
                    {req.priority}
                  </Badge>
                </div>
              </AccordionTrigger>
              <AccordionContent className="px-4 pb-3">
                <p className="mb-3">{req.description}</p>
                {req.dependencies && req.dependencies.length > 0 && (
                  <div>
                    <h4 className="font-medium mb-1">Dependencies</h4>
                    <div className="flex flex-wrap gap-1">
                      {req.dependencies.map((depId, idx) => (
                        <Badge key={idx} variant="outline">{depId}</Badge>
                      ))}
                    </div>
                  </div>
                )}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </section>

      {/* Testing & Validation Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Testing & Validation</h3>
        <div className="space-y-4">
          {prd.testing_validation.map((test, index) => (
            <Card key={index}>
              <CardHeader className="py-3">
                <CardTitle className="text-base">{test.test_type}</CardTitle>
              </CardHeader>
              <CardContent className="py-2 space-y-2">
                <div>
                  <h4 className="font-medium text-sm">Description</h4>
                  <p className="text-sm">{test.description}</p>
                </div>
                <div>
                  <h4 className="font-medium text-sm">Success Criteria</h4>
                  <p className="text-sm">{test.success_criteria}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Success Metrics Section */}
      <section>
        <h3 className="text-lg font-semibold mb-4">Technical Success Metrics</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {prd.success_metrics.map((metric, index) => (
            <Card key={index}>
              <CardHeader className="py-3">
                <CardTitle className="text-base">{metric.metric}</CardTitle>
              </CardHeader>
              <CardContent className="py-2 space-y-2">
                <div>
                  <h4 className="font-medium text-sm">Target</h4>
                  <p className="text-sm">{metric.target}</p>
                </div>
                <div>
                  <h4 className="font-medium text-sm">Measurement Method</h4>
                  <p className="text-sm">{metric.measurement_method}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>
    </div>
  );
}

export default PRDTab;
